# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Tuple, Union
from dnv_windfarmer_client.models.annual_energy_production_results import AnnualEnergyProductionResults
from dnv_windfarmer_client.models.calculation_status import CalculationStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AnnualEnergyProductionJobStatus(BaseModel):
    """
    Returns the status of an async AnnualEnergyProduction calculation.
    """ # noqa: E501
    progress: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gets the calculation progress, as a percentage between 0 and 100.")
    message: Optional[StrictStr] = Field(default=None, description="Gets a status message for the calculation as a whole.")
    stage_message: Optional[StrictStr] = Field(default=None, description="Gets a status message for the current stage of the calculation.", alias="stageMessage")
    status: Optional[CalculationStatus] = Field(default=None, description="Gets the calculation status (e.g. Pending, Executing, Faulted, Completed.")
    results: Optional[AnnualEnergyProductionResults] = Field(default=None, description="Gets the results of a completed calculation.")
    results_stream: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = Field(default=None, description="Gets a stream which can be used to retrieve the calculation results.", alias="resultsStream")
    __properties: ClassVar[List[str]] = ["progress", "message", "stageMessage", "status", "results", "resultsStream"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnnualEnergyProductionJobStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of results
        if self.results:
            _dict['results'] = self.results.to_dict()
        # set to None if results (nullable) is None
        # and model_fields_set contains the field
        if self.results is None and "results" in self.model_fields_set:
            _dict['results'] = None

        # set to None if results_stream (nullable) is None
        # and model_fields_set contains the field
        if self.results_stream is None and "results_stream" in self.model_fields_set:
            _dict['resultsStream'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnnualEnergyProductionJobStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "progress": obj.get("progress"),
            "message": obj.get("message"),
            "stageMessage": obj.get("stageMessage"),
            "status": obj.get("status"),
            "results": AnnualEnergyProductionResults.from_dict(obj["results"]) if obj.get("results") is not None else None,
            "resultsStream": obj.get("resultsStream")
        })
        return _obj


