# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AtmosphericConditionProbabilitySector(BaseModel):
    """
    An atmospheric condition probability distribution sector.
    """ # noqa: E501
    from_direction_degrees: Union[Annotated[float, Field(le=360, strict=True, ge=0)], Annotated[int, Field(le=360, strict=True, ge=0)]] = Field(description="Applies to flow cases with directions from and including direction.", alias="fromDirection_degrees")
    to_direction_degrees: Union[Annotated[float, Field(le=360, strict=True, ge=0)], Annotated[int, Field(le=360, strict=True, ge=0)]] = Field(description="Applies to flow cases with directions up to (excluding) direction.", alias="toDirection_degrees")
    atmospheric_condition_class_ids: Optional[List[StrictStr]] = Field(description="The order of atmospheric condition class IDs in the ProbabilityForClass list.", alias="atmosphericConditionClassIds")
    probability_for_classes: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="The probability for each of the specified AtmosphericConditionClassIds.  1.0 = 100% probability for the corresponding class.  The probabilities for a class are normalised to sum to 1.0 within this sector", alias="probabilityForClasses")
    __properties: ClassVar[List[str]] = ["fromDirection_degrees", "toDirection_degrees", "atmosphericConditionClassIds", "probabilityForClasses"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AtmosphericConditionProbabilitySector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if atmospheric_condition_class_ids (nullable) is None
        # and model_fields_set contains the field
        if self.atmospheric_condition_class_ids is None and "atmospheric_condition_class_ids" in self.model_fields_set:
            _dict['atmosphericConditionClassIds'] = None

        # set to None if probability_for_classes (nullable) is None
        # and model_fields_set contains the field
        if self.probability_for_classes is None and "probability_for_classes" in self.model_fields_set:
            _dict['probabilityForClasses'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AtmosphericConditionProbabilitySector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fromDirection_degrees": obj.get("fromDirection_degrees"),
            "toDirection_degrees": obj.get("toDirection_degrees"),
            "atmosphericConditionClassIds": obj.get("atmosphericConditionClassIds"),
            "probabilityForClasses": obj.get("probabilityForClasses")
        })
        return _obj


