# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.atmospheric_condition_class import AtmosphericConditionClass
from dnv_windfarmer_client.models.atmospheric_condition_probability_sector import AtmosphericConditionProbabilitySector
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AtmosphericConditions(BaseModel):
    """
    Contains the atmospheric condition information to enrich existing wind climates
    """ # noqa: E501
    atmospheric_condition_classes: Optional[List[AtmosphericConditionClass]] = Field(description="A list of atmospheric condition classes.", alias="atmosphericConditionClasses")
    atmospheric_condition_probability_distribution: Optional[List[AtmosphericConditionProbabilitySector]] = Field(description="Probability distribution describing by direction frequency of the atmospheric condition classes.", alias="atmosphericConditionProbabilityDistribution")
    __properties: ClassVar[List[str]] = ["atmosphericConditionClasses", "atmosphericConditionProbabilityDistribution"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AtmosphericConditions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in atmospheric_condition_classes (list)
        _items = []
        if self.atmospheric_condition_classes:
            for _item_atmospheric_condition_classes in self.atmospheric_condition_classes:
                _items.append(_item_atmospheric_condition_classes.to_dict() if _item_atmospheric_condition_classes is not None else None)
            _dict['atmosphericConditionClasses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in atmospheric_condition_probability_distribution (list)
        _items = []
        if self.atmospheric_condition_probability_distribution:
            for _item_atmospheric_condition_probability_distribution in self.atmospheric_condition_probability_distribution:
                _items.append(_item_atmospheric_condition_probability_distribution.to_dict() if _item_atmospheric_condition_probability_distribution is not None else None)
            _dict['atmosphericConditionProbabilityDistribution'] = _items
        # set to None if atmospheric_condition_classes (nullable) is None
        # and model_fields_set contains the field
        if self.atmospheric_condition_classes is None and "atmospheric_condition_classes" in self.model_fields_set:
            _dict['atmosphericConditionClasses'] = None

        # set to None if atmospheric_condition_probability_distribution (nullable) is None
        # and model_fields_set contains the field
        if self.atmospheric_condition_probability_distribution is None and "atmospheric_condition_probability_distribution" in self.model_fields_set:
            _dict['atmosphericConditionProbabilityDistribution'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AtmosphericConditions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "atmosphericConditionClasses": [AtmosphericConditionClass.from_dict(_item) for _item in obj["atmosphericConditionClasses"]] if obj.get("atmosphericConditionClasses") is not None else None,
            "atmosphericConditionProbabilityDistribution": [AtmosphericConditionProbabilitySector.from_dict(_item) for _item in obj["atmosphericConditionProbabilityDistribution"]] if obj.get("atmosphericConditionProbabilityDistribution") is not None else None
        })
        return _obj


