# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AtmosphericConditionClass(BaseModel):
    """
    An atmospheric condition class.
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="A unique atmospheric condition profile identifier.")
    boundary_layer_height_m: Union[Annotated[float, Field(le=5000, strict=True, ge=1)], Annotated[int, Field(le=5000, strict=True, ge=1)]] = Field(description="Boundary layer height. Units: m", alias="boundaryLayerHeight_m")
    lapse_rate_k_per_100m: Union[Annotated[float, Field(le=10, strict=True, ge=0)], Annotated[int, Field(le=10, strict=True, ge=0)]] = Field(description="Lapse rate in free atmosphere. Units: K/100m", alias="lapseRate_K_per_100m")
    delta_theta_across_inversion_layer_k: Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(description="Change in potential temperature across inversion layer. Units: K", alias="deltaThetaAcrossInversionLayer_K")
    thickness_inversion_layer_m: Union[Annotated[float, Field(le=2000, strict=True, ge=0)], Annotated[int, Field(le=2000, strict=True, ge=0)]] = Field(description="Thickness of inversion layer. Units: m", alias="thicknessInversionLayer_m")
    heights_above_surface_m: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=2)]] = Field(description="Heights above surface for which the List&lt;double&gt; AtmosphericConditionClass.TurbulenceIntensityProfile and List&lt;double&gt; AtmosphericConditionClass.WindSpeedVerticalGradientProfile profile parameters are defined.  Requires 2 or more elements that must be sorted in increasing order and cannot be negative. Units: m", alias="heightsAboveSurface_m")
    turbulence_intensity_profile: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="Turbulence intensity profile at heights defined in List&lt;double&gt; AtmosphericConditionClass.HeightsAboveSurface. Must have the same length as height above surface list. Units: fraction of mean wind speed (0 to 1)", alias="turbulenceIntensityProfile")
    wind_speed_vertical_gradient_profile_per_s_m: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="Wind speed vertical gradient profile at heights defined in List&lt;double&gt; AtmosphericConditionClass.HeightsAboveSurface. Must have the same length as height above surface list. Units: 1/s.m", alias="windSpeedVerticalGradientProfile_per_s_m")
    __properties: ClassVar[List[str]] = ["id", "boundaryLayerHeight_m", "lapseRate_K_per_100m", "deltaThetaAcrossInversionLayer_K", "thicknessInversionLayer_m", "heightsAboveSurface_m", "turbulenceIntensityProfile", "windSpeedVerticalGradientProfile_per_s_m"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AtmosphericConditionClass from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if heights_above_surface_m (nullable) is None
        # and model_fields_set contains the field
        if self.heights_above_surface_m is None and "heights_above_surface_m" in self.model_fields_set:
            _dict['heightsAboveSurface_m'] = None

        # set to None if turbulence_intensity_profile (nullable) is None
        # and model_fields_set contains the field
        if self.turbulence_intensity_profile is None and "turbulence_intensity_profile" in self.model_fields_set:
            _dict['turbulenceIntensityProfile'] = None

        # set to None if wind_speed_vertical_gradient_profile_per_s_m (nullable) is None
        # and model_fields_set contains the field
        if self.wind_speed_vertical_gradient_profile_per_s_m is None and "wind_speed_vertical_gradient_profile_per_s_m" in self.model_fields_set:
            _dict['windSpeedVerticalGradientProfile_per_s_m'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AtmosphericConditionClass from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "boundaryLayerHeight_m": obj.get("boundaryLayerHeight_m"),
            "lapseRate_K_per_100m": obj.get("lapseRate_K_per_100m"),
            "deltaThetaAcrossInversionLayer_K": obj.get("deltaThetaAcrossInversionLayer_K"),
            "thicknessInversionLayer_m": obj.get("thicknessInversionLayer_m"),
            "heightsAboveSurface_m": obj.get("heightsAboveSurface_m"),
            "turbulenceIntensityProfile": obj.get("turbulenceIntensityProfile"),
            "windSpeedVerticalGradientProfile_per_s_m": obj.get("windSpeedVerticalGradientProfile_per_s_m")
        })
        return _obj


