# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.turbine_location import TurbineLocation
from dnv_windfarmer_client.models.turbine_performance import TurbinePerformance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BeetModelInput(BaseModel):
    """
    Input model used for the calculation, includes turbine locations and performance curve.
    """ # noqa: E501
    turbines: Optional[List[TurbineLocation]] = Field(default=None, description="Details of the turbines on the wind farm.")
    turbine_performance: Optional[List[TurbinePerformance]] = Field(default=None, description="A list of turbine performance characteristics at different wind speeds.", alias="turbinePerformance")
    significant_atmospheric_stability: Optional[StrictBool] = Field(default=None, description="Specifies whether there is significant atmospheric stability (true), or if the atmosphere is predominantly neutral or unstable (false).", alias="significantAtmosphericStability")
    __properties: ClassVar[List[str]] = ["turbines", "turbinePerformance", "significantAtmosphericStability"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BeetModelInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in turbines (list)
        _items = []
        if self.turbines:
            for _item_turbines in self.turbines:
                _items.append(_item_turbines.to_dict() if _item_turbines is not None else None)
            _dict['turbines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_performance (list)
        _items = []
        if self.turbine_performance:
            for _item_turbine_performance in self.turbine_performance:
                _items.append(_item_turbine_performance.to_dict() if _item_turbine_performance is not None else None)
            _dict['turbinePerformance'] = _items
        # set to None if turbines (nullable) is None
        # and model_fields_set contains the field
        if self.turbines is None and "turbines" in self.model_fields_set:
            _dict['turbines'] = None

        # set to None if turbine_performance (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_performance is None and "turbine_performance" in self.model_fields_set:
            _dict['turbinePerformance'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BeetModelInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "turbines": [TurbineLocation.from_dict(_item) for _item in obj["turbines"]] if obj.get("turbines") is not None else None,
            "turbinePerformance": [TurbinePerformance.from_dict(_item) for _item in obj["turbinePerformance"]] if obj.get("turbinePerformance") is not None else None,
            "significantAtmosphericStability": obj.get("significantAtmosphericStability")
        })
        return _obj


