# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.weighted_beet_intermediate_data import WeightedBeetIntermediateData
from dnv_windfarmer_client.models.weighted_cfdml_intermediate_data import WeightedCfdmlIntermediateData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BlockageModelIntermediateData(BaseModel):
    """
    Blockage model intermediate data output
    """ # noqa: E501
    intermediate_data: Optional[WeightedBeetIntermediateData] = Field(default=None, description="The optional intermediate result data.", alias="intermediateData")
    intermediate_cfdml_v2_data: Optional[WeightedCfdmlIntermediateData] = Field(default=None, description="The per-flowcase, per-turbine blockage efficiencies for the CFDML V2 model.", alias="intermediateCfdmlV2Data")
    __properties: ClassVar[List[str]] = ["intermediateData", "intermediateCfdmlV2Data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlockageModelIntermediateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of intermediate_data
        if self.intermediate_data:
            _dict['intermediateData'] = self.intermediate_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of intermediate_cfdml_v2_data
        if self.intermediate_cfdml_v2_data:
            _dict['intermediateCfdmlV2Data'] = self.intermediate_cfdml_v2_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlockageModelIntermediateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "intermediateData": WeightedBeetIntermediateData.from_dict(obj["intermediateData"]) if obj.get("intermediateData") is not None else None,
            "intermediateCfdmlV2Data": WeightedCfdmlIntermediateData.from_dict(obj["intermediateCfdmlV2Data"]) if obj.get("intermediateCfdmlV2Data") is not None else None
        })
        return _obj


