# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.beet_settings import BeetSettings
from dnv_windfarmer_client.models.blockage_model_type import BlockageModelType
from dnv_windfarmer_client.models.cfdml_blockage_settings import CfdmlBlockageSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BlockageModelSettings(BaseModel):
    """
    The blockage model settings.
    """ # noqa: E501
    blockage_model_type: Optional[BlockageModelType] = Field(default=None, description="The blockage model to use.", alias="blockageModelType")
    beet: Optional[BeetSettings] = Field(default=None, description="DNV BEET model settings. Can be omitted if BlockageModelType is not BEET.")
    cfdml: Optional[CfdmlBlockageSettings] = Field(default=None, description="DNV CFD.ML model settings. Can be omitted if BlockageModelType is not CFD.ML.")
    __properties: ClassVar[List[str]] = ["blockageModelType", "beet", "cfdml"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlockageModelSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of beet
        if self.beet:
            _dict['beet'] = self.beet.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cfdml
        if self.cfdml:
            _dict['cfdml'] = self.cfdml.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlockageModelSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockageModelType": obj.get("blockageModelType"),
            "beet": BeetSettings.from_dict(obj["beet"]) if obj.get("beet") is not None else None,
            "cfdml": CfdmlBlockageSettings.from_dict(obj["cfdml"]) if obj.get("cfdml") is not None else None
        })
        return _obj


