# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.cfdml_wind_speed_extrapolation_model import CfdmlWindSpeedExtrapolationModel
from dnv_windfarmer_client.models.gnn_type import GnnType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Cfdml(BaseModel):
    """
    The CFD.ML wake model settings
    """ # noqa: E501
    gnn_type: Optional[GnnType] = Field(default=None, description="The GNN type to use in CFD.ML predictions", alias="gnnType")
    gnn_version: Optional[StrictStr] = Field(default='1.1', description="Version of the gnn to use. See release notes for the version number supported.", alias="gnnVersion")
    extrapolation_model: Optional[CfdmlWindSpeedExtrapolationModel] = Field(default=None, description="Model used to extrapolate Cfdml v2 single wind speed model.  Only relevant when defining Cfdml as a wake model. Ignored when defining Cfdml as a blockage model only. Required for Version &gt;= 2.0", alias="extrapolationModel")
    __properties: ClassVar[List[str]] = ["gnnType", "gnnVersion", "extrapolationModel"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cfdml from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gnn_version (nullable) is None
        # and model_fields_set contains the field
        if self.gnn_version is None and "gnn_version" in self.model_fields_set:
            _dict['gnnVersion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cfdml from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gnnType": obj.get("gnnType"),
            "gnnVersion": obj.get("gnnVersion") if "gnnVersion" in obj else '1.1',
            "extrapolationModel": obj.get("extrapolationModel")
        })
        return _obj


