# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.blockage_correction_application_method import BlockageCorrectionApplicationMethod
from dnv_windfarmer_client.models.cfdml import Cfdml
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CfdmlBlockageSettings(BaseModel):
    """
    The CFD.ML blockage model settings
    """ # noqa: E501
    cfdml_settings: Cfdml = Field(description="The CFD.ML model settings", alias="cfdmlSettings")
    include_intermediate_results: Optional[StrictBool] = Field(default=False, description="Gets or sets whether to include intermediate result data or not.", alias="includeIntermediateResults")
    blockage_correction_application_method: Optional[BlockageCorrectionApplicationMethod] = Field(default=None, description="Setting to specify whether to apply blockage correction on wind speed or on energy. Default value: OnEnergy.  Note: if includeBlockage == False this settings is ignored.", alias="blockageCorrectionApplicationMethod")
    __properties: ClassVar[List[str]] = ["cfdmlSettings", "includeIntermediateResults", "blockageCorrectionApplicationMethod"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CfdmlBlockageSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cfdml_settings
        if self.cfdml_settings:
            _dict['cfdmlSettings'] = self.cfdml_settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CfdmlBlockageSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cfdmlSettings": Cfdml.from_dict(obj["cfdmlSettings"]) if obj.get("cfdmlSettings") is not None else None,
            "includeIntermediateResults": obj.get("includeIntermediateResults") if obj.get("includeIntermediateResults") is not None else False,
            "blockageCorrectionApplicationMethod": obj.get("blockageCorrectionApplicationMethod")
        })
        return _obj


