# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CfdmlWindSpeedExtrapolationModel(str, Enum):
    """
    Extrapolate single wind speed Cfdml v2 results using the following model
    """

    """
    allowed enum values
    """
    BASICFLAT = 'BasicFlat'
    EDDYVISCOSITY = 'EddyViscosity'
    MODIFIEDPARK = 'ModifiedPark'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CfdmlWindSpeedExtrapolationModel from a JSON string"""
        return cls(json.loads(json_str))


