# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.atmospheric_conditions import AtmosphericConditions
from dnv_windfarmer_client.models.metadata import Metadata
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComprehensiveSiteClassification(BaseModel):
    """
    Comprehensive site classification result with metadata and atmospheric conditions
    """ # noqa: E501
    metadata: Optional[Metadata] = Field(default=None, description="Metadata about the site and analysis parameters")
    atmospheric_conditions: Optional[AtmosphericConditions] = Field(default=None, description="Atmospheric condition data compatible with WindFarmer calculations", alias="atmosphericConditions")
    __properties: ClassVar[List[str]] = ["metadata", "atmosphericConditions"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComprehensiveSiteClassification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of atmospheric_conditions
        if self.atmospheric_conditions:
            _dict['atmosphericConditions'] = self.atmospheric_conditions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComprehensiveSiteClassification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metadata": Metadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "atmosphericConditions": AtmosphericConditions.from_dict(obj["atmosphericConditions"]) if obj.get("atmosphericConditions") is not None else None
        })
        return _obj


