# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.large_wind_farm_correction_parameters import LargeWindFarmCorrectionParameters
from dnv_windfarmer_client.models.wake_profile_integration_method import WakeProfileIntegrationMethod
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EddyViscosity(BaseModel):
    """
    The Eddy Viscosity wake model settings
    """ # noqa: E501
    use_large_wind_farm_model: Optional[StrictBool] = Field(default=True, description="Wether to to use the large wind farm model. Default: true", alias="useLargeWindFarmModel")
    large_wind_farm_correction_parameters: Optional[LargeWindFarmCorrectionParameters] = Field(default=None, description="The large wind farm correction parameter values. Can be omited if useLargeWindFarmModel is false.", alias="largeWindFarmCorrectionParameters")
    use_closely_spaced_turbines_wake_modification: Optional[StrictBool] = Field(default=False, description="If true, the calculation will apply the closely spaced turbine modifications to the wake model when appropriate The calculation only applies modifications wakes from turbines that are less than 3D apart.", alias="useCloselySpacedTurbinesWakeModification")
    wake_profile_integration_method: Optional[WakeProfileIntegrationMethod] = Field(default=None, description="The method to use to combine multiple wakes when calculating the rotor averaged wind speed.", alias="wakeProfileIntegrationMethod")
    __properties: ClassVar[List[str]] = ["useLargeWindFarmModel", "largeWindFarmCorrectionParameters", "useCloselySpacedTurbinesWakeModification", "wakeProfileIntegrationMethod"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EddyViscosity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of large_wind_farm_correction_parameters
        if self.large_wind_farm_correction_parameters:
            _dict['largeWindFarmCorrectionParameters'] = self.large_wind_farm_correction_parameters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EddyViscosity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "useLargeWindFarmModel": obj.get("useLargeWindFarmModel") if obj.get("useLargeWindFarmModel") is not None else True,
            "largeWindFarmCorrectionParameters": LargeWindFarmCorrectionParameters.from_dict(obj["largeWindFarmCorrectionParameters"]) if obj.get("largeWindFarmCorrectionParameters") is not None else None,
            "useCloselySpacedTurbinesWakeModification": obj.get("useCloselySpacedTurbinesWakeModification") if obj.get("useCloselySpacedTurbinesWakeModification") is not None else False,
            "wakeProfileIntegrationMethod": obj.get("wakeProfileIntegrationMethod")
        })
        return _obj


