# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from dnv_windfarmer_client.models.air_density_correction_method import AirDensityCorrectionMethod
from dnv_windfarmer_client.models.blockage_model_settings import BlockageModelSettings
from dnv_windfarmer_client.models.extrapolation_ambient_turbulence import ExtrapolationAmbientTurbulence
from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_output_settings import TurbineFlowAndPerformanceMatrixOutputSettings
from dnv_windfarmer_client.models.wake_model_settings import WakeModelSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EnergyEfficienciesSettings(BaseModel):
    """
    The Annual Energy Production (AEP) calculation settings.
    """ # noqa: E501
    calculate_efficiencies: StrictBool = Field(description="If true, the energy calculation will be run several times so that the efficiencies can be calculated.", alias="calculateEfficiencies")
    calculate_ideal_yield: Optional[StrictBool] = Field(default=False, description="If true, the ideal (reference) yield is calculated.", alias="calculateIdealYield")
    calculate_sensitivity_curve: Optional[StrictBool] = Field(default=False, description="If true, wind speed perturbation to energy perturbation sensitivity curves are computed and returned in the results.", alias="calculateSensitivityCurve")
    include_hysteresis_effect: StrictBool = Field(description="If true, the high wind cut-out hysteresis effect will be included.", alias="includeHysteresisEffect")
    include_curtailment_rules: StrictBool = Field(description="If true, the turbine management rules will be applied.", alias="includeCurtailmentRules")
    turbine_flow_and_performance_matrix_output_settings: TurbineFlowAndPerformanceMatrixOutputSettings = Field(description="The output settings for the turbine flow and performance matrices.", alias="turbineFlowAndPerformanceMatrixOutputSettings")
    number_of_direction_sectors_for_wake_calculation: StrictInt = Field(description="The number of direction sectors to use for the wake calculation. Units: -", alias="numberOfDirectionSectorsForWakeCalculation")
    maximum_wind_speed_for_evaluation_m_per_s: Union[StrictFloat, StrictInt] = Field(description="If this is non-zero then all flow cases up to this mast wind speed will be evaluated and reported If this is zero, then flow cases will be evaluated for every wind-speed bin that has non-zero frequency of occurrence. Units: m/s", alias="maximumWindSpeedForEvaluation_m_per_s")
    extrapolation_ambient_turbulence: Optional[ExtrapolationAmbientTurbulence] = Field(default=None, description="The setting which defines whether to assume a constant std. dev. of wind speed or rather const. turbulence intensity.", alias="extrapolationAmbientTurbulence")
    air_density_correction_method: Optional[AirDensityCorrectionMethod] = Field(default=None, description="The method to use to extrapolate the power curve to the turbine location air density.", alias="airDensityCorrectionMethod")
    wake_model: WakeModelSettings = Field(description="The wake model settings.", alias="wakeModel")
    blockage_model: BlockageModelSettings = Field(description="The blockage model settings", alias="blockageModel")
    __properties: ClassVar[List[str]] = ["calculateEfficiencies", "calculateIdealYield", "calculateSensitivityCurve", "includeHysteresisEffect", "includeCurtailmentRules", "turbineFlowAndPerformanceMatrixOutputSettings", "numberOfDirectionSectorsForWakeCalculation", "maximumWindSpeedForEvaluation_m_per_s", "extrapolationAmbientTurbulence", "airDensityCorrectionMethod", "wakeModel", "blockageModel"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnergyEfficienciesSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of turbine_flow_and_performance_matrix_output_settings
        if self.turbine_flow_and_performance_matrix_output_settings:
            _dict['turbineFlowAndPerformanceMatrixOutputSettings'] = self.turbine_flow_and_performance_matrix_output_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wake_model
        if self.wake_model:
            _dict['wakeModel'] = self.wake_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of blockage_model
        if self.blockage_model:
            _dict['blockageModel'] = self.blockage_model.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnergyEfficienciesSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "calculateEfficiencies": obj.get("calculateEfficiencies"),
            "calculateIdealYield": obj.get("calculateIdealYield") if obj.get("calculateIdealYield") is not None else False,
            "calculateSensitivityCurve": obj.get("calculateSensitivityCurve") if obj.get("calculateSensitivityCurve") is not None else False,
            "includeHysteresisEffect": obj.get("includeHysteresisEffect"),
            "includeCurtailmentRules": obj.get("includeCurtailmentRules"),
            "turbineFlowAndPerformanceMatrixOutputSettings": TurbineFlowAndPerformanceMatrixOutputSettings.from_dict(obj["turbineFlowAndPerformanceMatrixOutputSettings"]) if obj.get("turbineFlowAndPerformanceMatrixOutputSettings") is not None else None,
            "numberOfDirectionSectorsForWakeCalculation": obj.get("numberOfDirectionSectorsForWakeCalculation"),
            "maximumWindSpeedForEvaluation_m_per_s": obj.get("maximumWindSpeedForEvaluation_m_per_s"),
            "extrapolationAmbientTurbulence": obj.get("extrapolationAmbientTurbulence"),
            "airDensityCorrectionMethod": obj.get("airDensityCorrectionMethod"),
            "wakeModel": WakeModelSettings.from_dict(obj["wakeModel"]) if obj.get("wakeModel") is not None else None,
            "blockageModel": BlockageModelSettings.from_dict(obj["blockageModel"]) if obj.get("blockageModel") is not None else None
        })
        return _obj


