# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.atmospheric_conditions import AtmosphericConditions
from dnv_windfarmer_client.models.energy_efficiencies_settings import EnergyEfficienciesSettings
from dnv_windfarmer_client.models.flow_model import FlowModel
from dnv_windfarmer_client.models.project_info import ProjectInfo
from dnv_windfarmer_client.models.reference_air_density import ReferenceAirDensity
from dnv_windfarmer_client.models.turbine_model import TurbineModel
from dnv_windfarmer_client.models.weibull_wind_climate import WeibullWindClimate
from dnv_windfarmer_client.models.wind_climate import WindClimate
from dnv_windfarmer_client.models.wind_farm import WindFarm
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EnergyCalculationInputs(BaseModel):
    """
    A class for holding all the calculation inputs required for the energy calculation.
    """ # noqa: E501
    project_info: ProjectInfo = Field(description="Project information.", alias="projectInfo")
    wind_farms: Optional[List[WindFarm]] = Field(description="Wind farms to be included in the analysis.", alias="windFarms")
    turbine_models: Optional[List[TurbineModel]] = Field(description="Turbine models used in the wind farms.", alias="turbineModels")
    wind_climates: Optional[List[WindClimate]] = Field(default=None, description="The wind climate data provided as frequency and turbulence distributions. For use when this measured data exists. If this list is specified then the List&lt;WeibullWindClimate&gt; EnergyCalculationInputs.WeibullWindClimates list should not be specified.", alias="windClimates")
    weibull_wind_climates: Optional[List[WeibullWindClimate]] = Field(default=None, description="The wind climate data provided as weibull parameters for probabilities and a single turbulence value. For use when measured data is not available. If this list is specified then the List&lt;WindClimate&gt; EnergyCalculationInputs.WindClimates list should not be specified.", alias="weibullWindClimates")
    atmospheric_conditions: Optional[AtmosphericConditions] = Field(default=None, description="The atmospheric conditions that apply to existing wind climates.", alias="atmosphericConditions")
    reference_air_density: ReferenceAirDensity = Field(description="The reference air density for the wind farm.", alias="referenceAirDensity")
    flow_model: FlowModel = Field(description="The flow model data.", alias="flowModel")
    energy_efficiencies_settings: EnergyEfficienciesSettings = Field(description="The calculation settings.", alias="energyEfficienciesSettings")
    __properties: ClassVar[List[str]] = ["projectInfo", "windFarms", "turbineModels", "windClimates", "weibullWindClimates", "atmosphericConditions", "referenceAirDensity", "flowModel", "energyEfficienciesSettings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnergyCalculationInputs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of project_info
        if self.project_info:
            _dict['projectInfo'] = self.project_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in wind_farms (list)
        _items = []
        if self.wind_farms:
            for _item_wind_farms in self.wind_farms:
                _items.append(_item_wind_farms.to_dict() if _item_wind_farms is not None else None)
            _dict['windFarms'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_models (list)
        _items = []
        if self.turbine_models:
            for _item_turbine_models in self.turbine_models:
                _items.append(_item_turbine_models.to_dict() if _item_turbine_models is not None else None)
            _dict['turbineModels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in wind_climates (list)
        _items = []
        if self.wind_climates:
            for _item_wind_climates in self.wind_climates:
                _items.append(_item_wind_climates.to_dict() if _item_wind_climates is not None else None)
            _dict['windClimates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in weibull_wind_climates (list)
        _items = []
        if self.weibull_wind_climates:
            for _item_weibull_wind_climates in self.weibull_wind_climates:
                _items.append(_item_weibull_wind_climates.to_dict() if _item_weibull_wind_climates is not None else None)
            _dict['weibullWindClimates'] = _items
        # override the default output from pydantic by calling `to_dict()` of atmospheric_conditions
        if self.atmospheric_conditions:
            _dict['atmosphericConditions'] = self.atmospheric_conditions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reference_air_density
        if self.reference_air_density:
            _dict['referenceAirDensity'] = self.reference_air_density.to_dict()
        # override the default output from pydantic by calling `to_dict()` of flow_model
        if self.flow_model:
            _dict['flowModel'] = self.flow_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of energy_efficiencies_settings
        if self.energy_efficiencies_settings:
            _dict['energyEfficienciesSettings'] = self.energy_efficiencies_settings.to_dict()
        # set to None if wind_farms (nullable) is None
        # and model_fields_set contains the field
        if self.wind_farms is None and "wind_farms" in self.model_fields_set:
            _dict['windFarms'] = None

        # set to None if turbine_models (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_models is None and "turbine_models" in self.model_fields_set:
            _dict['turbineModels'] = None

        # set to None if wind_climates (nullable) is None
        # and model_fields_set contains the field
        if self.wind_climates is None and "wind_climates" in self.model_fields_set:
            _dict['windClimates'] = None

        # set to None if weibull_wind_climates (nullable) is None
        # and model_fields_set contains the field
        if self.weibull_wind_climates is None and "weibull_wind_climates" in self.model_fields_set:
            _dict['weibullWindClimates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnergyCalculationInputs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "projectInfo": ProjectInfo.from_dict(obj["projectInfo"]) if obj.get("projectInfo") is not None else None,
            "windFarms": [WindFarm.from_dict(_item) for _item in obj["windFarms"]] if obj.get("windFarms") is not None else None,
            "turbineModels": [TurbineModel.from_dict(_item) for _item in obj["turbineModels"]] if obj.get("turbineModels") is not None else None,
            "windClimates": [WindClimate.from_dict(_item) for _item in obj["windClimates"]] if obj.get("windClimates") is not None else None,
            "weibullWindClimates": [WeibullWindClimate.from_dict(_item) for _item in obj["weibullWindClimates"]] if obj.get("weibullWindClimates") is not None else None,
            "atmosphericConditions": AtmosphericConditions.from_dict(obj["atmosphericConditions"]) if obj.get("atmosphericConditions") is not None else None,
            "referenceAirDensity": ReferenceAirDensity.from_dict(obj["referenceAirDensity"]) if obj.get("referenceAirDensity") is not None else None,
            "flowModel": FlowModel.from_dict(obj["flowModel"]) if obj.get("flowModel") is not None else None,
            "energyEfficienciesSettings": EnergyEfficienciesSettings.from_dict(obj["energyEfficienciesSettings"]) if obj.get("energyEfficienciesSettings") is not None else None
        })
        return _obj


