# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from dnv_windfarmer_client.models.speed_ups_for_location import SpeedUpsForLocation
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FlowModel(BaseModel):
    """
    The flow model data.
    """ # noqa: E501
    reference_directions_degrees: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="The reference wind directions for each of the speedups provided. A sorted array is expected.", alias="referenceDirections_degrees")
    speeds_ups: Optional[List[SpeedUpsForLocation]] = Field(description="The relative speedups at each location.", alias="speedsUps")
    __properties: ClassVar[List[str]] = ["referenceDirections_degrees", "speedsUps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlowModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in speeds_ups (list)
        _items = []
        if self.speeds_ups:
            for _item_speeds_ups in self.speeds_ups:
                _items.append(_item_speeds_ups.to_dict() if _item_speeds_ups is not None else None)
            _dict['speedsUps'] = _items
        # set to None if reference_directions_degrees (nullable) is None
        # and model_fields_set contains the field
        if self.reference_directions_degrees is None and "reference_directions_degrees" in self.model_fields_set:
            _dict['referenceDirections_degrees'] = None

        # set to None if speeds_ups (nullable) is None
        # and model_fields_set contains the field
        if self.speeds_ups is None and "speeds_ups" in self.model_fields_set:
            _dict['speedsUps'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlowModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "referenceDirections_degrees": obj.get("referenceDirections_degrees"),
            "speedsUps": [SpeedUpsForLocation.from_dict(_item) for _item in obj["speedsUps"]] if obj.get("speedsUps") is not None else None
        })
        return _obj


