# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from dnv_windfarmer_client.models.beet_model_input import BeetModelInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntermediateBeetRun(BaseModel):
    """
    A class to hold an intermediate blockage run.
    """ # noqa: E501
    blockage_input: Optional[BeetModelInput] = Field(default=None, description="Gets or sets the blockage model input.", alias="blockageInput")
    turbine_model_name: Optional[StrictStr] = Field(default=None, description="The turbine model name.", alias="turbineModelName")
    hub_height: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The turbine model hub height", alias="hubHeight")
    average_air_density_at_hub_height: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The average air density at hub height.", alias="averageAirDensityAtHubHeight")
    wind_climate_name: Optional[StrictStr] = Field(default=None, description="The wind climate name.", alias="windClimateName")
    average_adjusted_free_stream_mean_wind_speed: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The average adjusted free stream mean wind speed.", alias="averageAdjustedFreeStreamMeanWindSpeed")
    weighted_result: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The weighted result.", alias="weightedResult")
    blockage_effect: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The blockage effect.", alias="blockageEffect")
    density_rotor_diameters: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gets the density rotor diameters (Internal use only).", alias="densityRotorDiameters")
    blockage_loss_ws: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gets the blockage loss wind speed percentage (Internal use only).", alias="blockageLossWs")
    hub_height_rotor_diameter_multiplier: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gets the hub height rotor diameter multiplier (Internal use only).", alias="hubHeightRotorDiameterMultiplier")
    __properties: ClassVar[List[str]] = ["blockageInput", "turbineModelName", "hubHeight", "averageAirDensityAtHubHeight", "windClimateName", "averageAdjustedFreeStreamMeanWindSpeed", "weightedResult", "blockageEffect", "densityRotorDiameters", "blockageLossWs", "hubHeightRotorDiameterMultiplier"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntermediateBeetRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of blockage_input
        if self.blockage_input:
            _dict['blockageInput'] = self.blockage_input.to_dict()
        # set to None if turbine_model_name (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_model_name is None and "turbine_model_name" in self.model_fields_set:
            _dict['turbineModelName'] = None

        # set to None if wind_climate_name (nullable) is None
        # and model_fields_set contains the field
        if self.wind_climate_name is None and "wind_climate_name" in self.model_fields_set:
            _dict['windClimateName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntermediateBeetRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockageInput": BeetModelInput.from_dict(obj["blockageInput"]) if obj.get("blockageInput") is not None else None,
            "turbineModelName": obj.get("turbineModelName"),
            "hubHeight": obj.get("hubHeight"),
            "averageAirDensityAtHubHeight": obj.get("averageAirDensityAtHubHeight"),
            "windClimateName": obj.get("windClimateName"),
            "averageAdjustedFreeStreamMeanWindSpeed": obj.get("averageAdjustedFreeStreamMeanWindSpeed"),
            "weightedResult": obj.get("weightedResult"),
            "blockageEffect": obj.get("blockageEffect"),
            "densityRotorDiameters": obj.get("densityRotorDiameters"),
            "blockageLossWs": obj.get("blockageLossWs"),
            "hubHeightRotorDiameterMultiplier": obj.get("hubHeightRotorDiameterMultiplier")
        })
        return _obj


