# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LargeWindFarmCorrectionParameters(BaseModel):
    """
    The large wind farm correction parameter values.
    """ # noqa: E501
    base_roughness_z01: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Base Roughness Z01.", alias="baseRoughnessZ01")
    increased_roughness_z02: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Increased Roughness Z02.", alias="increasedRoughnessZ02")
    geometric_width_diameters: Optional[Union[StrictFloat, StrictInt]] = Field(default=1, description="Geometric Width Diameters.", alias="geometricWidthDiameters")
    recovery_start_diameters: Optional[Union[StrictFloat, StrictInt]] = Field(default=60, description="Recovery Start Diameters.", alias="recoveryStartDiameters")
    fifty_percent_recovery_diameters: Optional[Union[StrictFloat, StrictInt]] = Field(default=40, description="Fifty Percent Recovery Diameters.", alias="fiftyPercentRecoveryDiameters")
    __properties: ClassVar[List[str]] = ["baseRoughnessZ01", "increasedRoughnessZ02", "geometricWidthDiameters", "recoveryStartDiameters", "fiftyPercentRecoveryDiameters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LargeWindFarmCorrectionParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LargeWindFarmCorrectionParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "baseRoughnessZ01": obj.get("baseRoughnessZ01"),
            "increasedRoughnessZ02": obj.get("increasedRoughnessZ02"),
            "geometricWidthDiameters": obj.get("geometricWidthDiameters") if obj.get("geometricWidthDiameters") is not None else 1,
            "recoveryStartDiameters": obj.get("recoveryStartDiameters") if obj.get("recoveryStartDiameters") is not None else 60,
            "fiftyPercentRecoveryDiameters": obj.get("fiftyPercentRecoveryDiameters") if obj.get("fiftyPercentRecoveryDiameters") is not None else 40
        })
        return _obj


