# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Metadata(BaseModel):
    """
    Metadata about the site classification analysis
    """ # noqa: E501
    site_latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the site", alias="siteLatitude")
    site_longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the site", alias="siteLongitude")
    nearest_era5_grid_latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Latitude of the nearest Era5 grid point", alias="nearestEra5GridLatitude")
    nearest_era5_grid_longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Longitude of the nearest Era5 grid point", alias="nearestEra5GridLongitude")
    distance_to_nearest_grid_point_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Distance to the nearest Era5 grid point in kilometers", alias="distanceToNearestGridPoint_km")
    number_of_sectors: Optional[StrictInt] = Field(default=None, description="Number of directional sectors used in the analysis", alias="numberOfSectors")
    coastline_detection_radius_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Radius in kilometers used for coastline detection", alias="coastlineDetectionRadius_km")
    stability_classification_method: Optional[StrictStr] = Field(default=None, description="Method used for stability classification (e.g., \"hf\", \"mol\", \"blend\")", alias="stabilityClassificationMethod")
    era5_time_series_start_date: Optional[StrictStr] = Field(default=None, description="Start date of the Era5 time series data", alias="era5TimeSeriesStartDate")
    era5_time_series_end_date: Optional[StrictStr] = Field(default=None, description="End date of the Era5 time series data", alias="era5TimeSeriesEndDate")
    __properties: ClassVar[List[str]] = ["siteLatitude", "siteLongitude", "nearestEra5GridLatitude", "nearestEra5GridLongitude", "distanceToNearestGridPoint_km", "numberOfSectors", "coastlineDetectionRadius_km", "stabilityClassificationMethod", "era5TimeSeriesStartDate", "era5TimeSeriesEndDate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Metadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if era5_time_series_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.era5_time_series_start_date is None and "era5_time_series_start_date" in self.model_fields_set:
            _dict['era5TimeSeriesStartDate'] = None

        # set to None if era5_time_series_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.era5_time_series_end_date is None and "era5_time_series_end_date" in self.model_fields_set:
            _dict['era5TimeSeriesEndDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Metadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "siteLatitude": obj.get("siteLatitude"),
            "siteLongitude": obj.get("siteLongitude"),
            "nearestEra5GridLatitude": obj.get("nearestEra5GridLatitude"),
            "nearestEra5GridLongitude": obj.get("nearestEra5GridLongitude"),
            "distanceToNearestGridPoint_km": obj.get("distanceToNearestGridPoint_km"),
            "numberOfSectors": obj.get("numberOfSectors"),
            "coastlineDetectionRadius_km": obj.get("coastlineDetectionRadius_km"),
            "stabilityClassificationMethod": obj.get("stabilityClassificationMethod"),
            "era5TimeSeriesStartDate": obj.get("era5TimeSeriesStartDate"),
            "era5TimeSeriesEndDate": obj.get("era5TimeSeriesEndDate")
        })
        return _obj


