# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReferenceAirDensity(BaseModel):
    """
    The reference air density and elevation.
    """ # noqa: E501
    air_density_kg_per_m3: Union[StrictFloat, StrictInt] = Field(description="The reference air density.  Units: kg/m3", alias="airDensity_kg_per_m3")
    lapse_rate_kg_per_m3_per_m: Union[StrictFloat, StrictInt] = Field(description="The reference air density lapse rate.  Units: (kg/m3)/m", alias="lapseRate_kg_per_m3_per_m")
    elevation_m: Union[StrictFloat, StrictInt] = Field(description="The elevation of the reference air density.  Units: m")
    __properties: ClassVar[List[str]] = ["airDensity_kg_per_m3", "lapseRate_kg_per_m3_per_m", "elevation_m"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReferenceAirDensity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReferenceAirDensity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "airDensity_kg_per_m3": obj.get("airDensity_kg_per_m3"),
            "lapseRate_kg_per_m3_per_m": obj.get("lapseRate_kg_per_m3_per_m"),
            "elevation_m": obj.get("elevation_m")
        })
        return _obj


