# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.overall_sensitivity_curve import OverallSensitivityCurve
from dnv_windfarmer_client.models.turbine_sensitivity_curve import TurbineSensitivityCurve
from dnv_windfarmer_client.models.wind_climate_sensitivity_curve import WindClimateSensitivityCurve
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SensitivityCurveCalculationOutputs(BaseModel):
    """
    A class for holding the sensitivity curve calculation results.
    """ # noqa: E501
    overall_sensitivity_curve: Optional[OverallSensitivityCurve] = Field(default=None, description="Gets or sets the overall sensitivity curve DTO.", alias="overallSensitivityCurve")
    wind_climate_sensitivity_curves: Optional[List[WindClimateSensitivityCurve]] = Field(default=None, description="Gets or sets the wind climate sensitivity curve DTOs.", alias="windClimateSensitivityCurves")
    turbine_sensitivity_curves: Optional[List[TurbineSensitivityCurve]] = Field(default=None, description="Gets or sets the turbine climate sensitivity curve DTOs.", alias="turbineSensitivityCurves")
    __properties: ClassVar[List[str]] = ["overallSensitivityCurve", "windClimateSensitivityCurves", "turbineSensitivityCurves"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SensitivityCurveCalculationOutputs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of overall_sensitivity_curve
        if self.overall_sensitivity_curve:
            _dict['overallSensitivityCurve'] = self.overall_sensitivity_curve.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in wind_climate_sensitivity_curves (list)
        _items = []
        if self.wind_climate_sensitivity_curves:
            for _item_wind_climate_sensitivity_curves in self.wind_climate_sensitivity_curves:
                _items.append(_item_wind_climate_sensitivity_curves.to_dict() if _item_wind_climate_sensitivity_curves is not None else None)
            _dict['windClimateSensitivityCurves'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_sensitivity_curves (list)
        _items = []
        if self.turbine_sensitivity_curves:
            for _item_turbine_sensitivity_curves in self.turbine_sensitivity_curves:
                _items.append(_item_turbine_sensitivity_curves.to_dict() if _item_turbine_sensitivity_curves is not None else None)
            _dict['turbineSensitivityCurves'] = _items
        # set to None if wind_climate_sensitivity_curves (nullable) is None
        # and model_fields_set contains the field
        if self.wind_climate_sensitivity_curves is None and "wind_climate_sensitivity_curves" in self.model_fields_set:
            _dict['windClimateSensitivityCurves'] = None

        # set to None if turbine_sensitivity_curves (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_sensitivity_curves is None and "turbine_sensitivity_curves" in self.model_fields_set:
            _dict['turbineSensitivityCurves'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SensitivityCurveCalculationOutputs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "overallSensitivityCurve": OverallSensitivityCurve.from_dict(obj["overallSensitivityCurve"]) if obj.get("overallSensitivityCurve") is not None else None,
            "windClimateSensitivityCurves": [WindClimateSensitivityCurve.from_dict(_item) for _item in obj["windClimateSensitivityCurves"]] if obj.get("windClimateSensitivityCurves") is not None else None,
            "turbineSensitivityCurves": [TurbineSensitivityCurve.from_dict(_item) for _item in obj["turbineSensitivityCurves"]] if obj.get("turbineSensitivityCurves") is not None else None
        })
        return _obj


