# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SpeedUpsForLocation(BaseModel):
    """
    The relative speedup data for one location. An instance of this class should always be part of a FlowModel
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="Unique identifier for a flow model point. Used to match to a turbine or wind climate. Expected format is:   * For turbines: [WindFarm Name]space[Turbine Name]   * For Wind climates: The wind climate Id string WindClimate.Id or string WeibullWindClimate.Id")
    easting_m: Union[StrictFloat, StrictInt] = Field(description="Gets the easting. Units: m.")
    northing_m: Union[StrictFloat, StrictInt] = Field(description="Gets the northing. Units: m.")
    height_above_ground_m: Union[StrictFloat, StrictInt] = Field(description="Gets the height above ground. Units: m.", alias="heightAboveGround_m")
    speed_ups: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="The speedup values for each wind direction.", alias="speedUps")
    is_target: Optional[StrictBool] = Field(default=True, description="Whether these speed ups refer to a target (usually turbine) or a source (usually measurement site).  For backwards compatibility this defaults: true", alias="isTarget")
    __properties: ClassVar[List[str]] = ["id", "easting_m", "northing_m", "heightAboveGround_m", "speedUps", "isTarget"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpeedUpsForLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if speed_ups (nullable) is None
        # and model_fields_set contains the field
        if self.speed_ups is None and "speed_ups" in self.model_fields_set:
            _dict['speedUps'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpeedUpsForLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "easting_m": obj.get("easting_m"),
            "northing_m": obj.get("northing_m"),
            "heightAboveGround_m": obj.get("heightAboveGround_m"),
            "speedUps": obj.get("speedUps"),
            "isTarget": obj.get("isTarget") if obj.get("isTarget") is not None else True
        })
        return _obj


