# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(BaseModel):
    """
    The output settings for flow and performance matrices in local turbine wind speeds
    """ # noqa: E501
    output_power_output: Optional[StrictBool] = Field(default=False, description="If true the Power Output with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputPowerOutput")
    output_waked_wind_speed: Optional[StrictBool] = Field(default=False, description="If true the Waked Wind Speed with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputWakedWindSpeed")
    output_probability_distribution: Optional[StrictBool] = Field(default=False, description="If true the Probabilities distribution with local turbine wind speeds flow and performance matrix will be output by the calculation.", alias="outputProbabilityDistribution")
    output_waked_turbulence_intensity: Optional[StrictBool] = Field(default=False, description="If true the Waked Turbulence Intensity with local turbine wind speeds flow and performance matrix will be output by the calculation.", alias="outputWakedTurbulenceIntensity")
    output_ambient_turbulence_intensity: Optional[StrictBool] = Field(default=False, description="If true the Ambient Turbulence Intensity with local turbine wind speeds flow and performance matrix will be output by the calculation.", alias="outputAmbientTurbulenceIntensity")
    output_operational_mode: Optional[StrictBool] = Field(default=False, description="If true the Operation model with local turbine wind speeds flow and performance matrix will be output by the calculation.", alias="outputOperationalMode")
    __properties: ClassVar[List[str]] = ["outputPowerOutput", "outputWakedWindSpeed", "outputProbabilityDistribution", "outputWakedTurbulenceIntensity", "outputAmbientTurbulenceIntensity", "outputOperationalMode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "outputPowerOutput": obj.get("outputPowerOutput") if obj.get("outputPowerOutput") is not None else False,
            "outputWakedWindSpeed": obj.get("outputWakedWindSpeed") if obj.get("outputWakedWindSpeed") is not None else False,
            "outputProbabilityDistribution": obj.get("outputProbabilityDistribution") if obj.get("outputProbabilityDistribution") is not None else False,
            "outputWakedTurbulenceIntensity": obj.get("outputWakedTurbulenceIntensity") if obj.get("outputWakedTurbulenceIntensity") is not None else False,
            "outputAmbientTurbulenceIntensity": obj.get("outputAmbientTurbulenceIntensity") if obj.get("outputAmbientTurbulenceIntensity") is not None else False,
            "outputOperationalMode": obj.get("outputOperationalMode") if obj.get("outputOperationalMode") is not None else False
        })
        return _obj


