# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.power_control_type import PowerControlType
from dnv_windfarmer_client.models.turbine_model_performance import TurbineModelPerformance
from dnv_windfarmer_client.models.turbulence_intensity_class import TurbulenceIntensityClass
from dnv_windfarmer_client.models.wind_speed_class import WindSpeedClass
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineModel(BaseModel):
    """
    Model data for a particular Turbine model.
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="The unique id of the turbine model.")
    rotor_diameter_m: Union[StrictFloat, StrictInt] = Field(description="The diameter of the turbine rotor.  Units: m", alias="rotorDiameter_m")
    number_of_blades: StrictInt = Field(description="The number of blades. Units: -", alias="numberOfBlades")
    hub_height_m: Union[StrictFloat, StrictInt] = Field(description="The height of the hub above the turbine base.  Units: m", alias="hubHeight_m")
    performance_data: Optional[List[TurbineModelPerformance]] = Field(description="The performance specific data.", alias="performanceData")
    power_control: PowerControlType = Field(description="The power control type of the turbine.", alias="powerControl")
    wind_speed_class: Optional[WindSpeedClass] = Field(default=None, description="Wind speed class as per IEC edition 3 standard - '1', '2', '3'.", alias="windSpeedClass")
    turbulence_intensity_class: Optional[TurbulenceIntensityClass] = Field(default=None, description="Turbulence intensity class as per IEC edition 3 standard - 'A', 'B', 'C'.", alias="turbulenceIntensityClass")
    reference_noise_level: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Reference noise level for this turbine. dB TODO this is a dummy really - need a whole noise DTO here including octave bands etc.", alias="referenceNoiseLevel")
    __properties: ClassVar[List[str]] = ["id", "rotorDiameter_m", "numberOfBlades", "hubHeight_m", "performanceData", "powerControl", "windSpeedClass", "turbulenceIntensityClass", "referenceNoiseLevel"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in performance_data (list)
        _items = []
        if self.performance_data:
            for _item_performance_data in self.performance_data:
                _items.append(_item_performance_data.to_dict() if _item_performance_data is not None else None)
            _dict['performanceData'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if performance_data (nullable) is None
        # and model_fields_set contains the field
        if self.performance_data is None and "performance_data" in self.model_fields_set:
            _dict['performanceData'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "rotorDiameter_m": obj.get("rotorDiameter_m"),
            "numberOfBlades": obj.get("numberOfBlades"),
            "hubHeight_m": obj.get("hubHeight_m"),
            "performanceData": [TurbineModelPerformance.from_dict(_item) for _item in obj["performanceData"]] if obj.get("performanceData") is not None else None,
            "powerControl": obj.get("powerControl"),
            "windSpeedClass": obj.get("windSpeedClass"),
            "turbulenceIntensityClass": obj.get("turbulenceIntensityClass"),
            "referenceNoiseLevel": obj.get("referenceNoiseLevel")
        })
        return _obj


