# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_local_wind_speeds_output_settings import TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineFlowAndPerformanceMatrixOutputSettings(BaseModel):
    """
    The output settings for the turbine flow and performance matrices.
    """ # noqa: E501
    output_mast_to_turbine_speed_up: Optional[StrictBool] = Field(default=False, description="If true the mast to turbine speedup will be output by the calculation.", alias="outputMastToTurbineSpeedUp")
    output_ambient_wind_speed: Optional[StrictBool] = Field(default=False, description="If true the Ambient Wind Speed with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputAmbientWindSpeed")
    output_ambient_turbulence_intensity: Optional[StrictBool] = Field(default=False, description="If true the Ambient Turbulence Intensity with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputAmbientTurbulenceIntensity")
    output_dominant_wake_center_line_wind_speed: Optional[StrictBool] = Field(default=False, description="If true the Dominant Wake Center-line Wind Speed with reference wind speeds at the mast flow and performance matrix will be output by the calculation. FPM is only available for wake models EddyViscosity and ModifiedPark.", alias="outputDominantWakeCenterLineWindSpeed")
    output_dominant_wake_offset: Optional[StrictBool] = Field(default=False, description="If true the Dominant Wake Offset with reference wind speeds at the mast flow and performance matrix will be output by the calculation. FPM is only available for wake models EddyViscosity and ModifiedPark.", alias="outputDominantWakeOffset")
    output_dominant_wake_width: Optional[StrictBool] = Field(default=False, description="If true the Dominant Wake Width with reference wind speeds at the mast flow and performance matrix will be output by the calculation. FPM is only available for wake model EddyViscosity.", alias="outputDominantWakeWidth")
    output_waked_wind_speed: Optional[StrictBool] = Field(default=False, description="If true the Waked Wind Speed with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputWakedWindSpeed")
    output_atmospheric_aware_waked_wind_speed: Optional[StrictBool] = Field(default=False, description="If true the Atmospheric Condition Aware Waked Wind Speed flow and performance matrix, with reference wind speeds at the mast, will be output by the calculation. FPM is only available for wake model CFD.ML v2.0 and later.", alias="outputAtmosphericAwareWakedWindSpeed")
    output_waked_turbulence_intensity: Optional[StrictBool] = Field(default=False, description="If true the Waked Turbulence Intensity with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputWakedTurbulenceIntensity")
    output_power_output: Optional[StrictBool] = Field(default=False, description="If true the Power Output with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputPowerOutput")
    output_atmospheric_aware_power_output: Optional[StrictBool] = Field(default=False, description="If true the Atmospheric Condition Aware Power Output with reference wind speeds at the mast flow and performance matrix will be output by the calculation. FPM is only available for wake model CFD.ML v2.0 and later.", alias="outputAtmosphericAwarePowerOutput")
    output_probability_distribution: Optional[StrictBool] = Field(default=False, description="If true the Probabilities distribution with reference wind speeds at the mast flow and performance matrix will be output by the calculation.", alias="outputProbabilityDistribution")
    output_upstream_turbine_causing_wake: Optional[StrictBool] = Field(default=False, description="If true the Upstream Turbine Name causing wake with reference wind speeds at the mast flow and performance matrix will be output by the calculation. FPM is only available for wake models EddyViscosity and ModifiedPark.", alias="outputUpstreamTurbineCausingWake")
    output_operational_mode: Optional[StrictBool] = Field(default=False, description="If true the turbine operational mode for the turbine with reference wind speeds at the mast flow and performance matrix will be output", alias="outputOperationalMode")
    local_turbine_wind_speeds_output_settings: Optional[TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings] = Field(default=None, description="The output settings for the flow and performance matrices with local turbine wind speeds as reference. Only fill this property in json if matrices in local wind speeds are needed, otherwise omit the property.", alias="localTurbineWindSpeedsOutputSettings")
    __properties: ClassVar[List[str]] = ["outputMastToTurbineSpeedUp", "outputAmbientWindSpeed", "outputAmbientTurbulenceIntensity", "outputDominantWakeCenterLineWindSpeed", "outputDominantWakeOffset", "outputDominantWakeWidth", "outputWakedWindSpeed", "outputAtmosphericAwareWakedWindSpeed", "outputWakedTurbulenceIntensity", "outputPowerOutput", "outputAtmosphericAwarePowerOutput", "outputProbabilityDistribution", "outputUpstreamTurbineCausingWake", "outputOperationalMode", "localTurbineWindSpeedsOutputSettings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrixOutputSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of local_turbine_wind_speeds_output_settings
        if self.local_turbine_wind_speeds_output_settings:
            _dict['localTurbineWindSpeedsOutputSettings'] = self.local_turbine_wind_speeds_output_settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrixOutputSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "outputMastToTurbineSpeedUp": obj.get("outputMastToTurbineSpeedUp") if obj.get("outputMastToTurbineSpeedUp") is not None else False,
            "outputAmbientWindSpeed": obj.get("outputAmbientWindSpeed") if obj.get("outputAmbientWindSpeed") is not None else False,
            "outputAmbientTurbulenceIntensity": obj.get("outputAmbientTurbulenceIntensity") if obj.get("outputAmbientTurbulenceIntensity") is not None else False,
            "outputDominantWakeCenterLineWindSpeed": obj.get("outputDominantWakeCenterLineWindSpeed") if obj.get("outputDominantWakeCenterLineWindSpeed") is not None else False,
            "outputDominantWakeOffset": obj.get("outputDominantWakeOffset") if obj.get("outputDominantWakeOffset") is not None else False,
            "outputDominantWakeWidth": obj.get("outputDominantWakeWidth") if obj.get("outputDominantWakeWidth") is not None else False,
            "outputWakedWindSpeed": obj.get("outputWakedWindSpeed") if obj.get("outputWakedWindSpeed") is not None else False,
            "outputAtmosphericAwareWakedWindSpeed": obj.get("outputAtmosphericAwareWakedWindSpeed") if obj.get("outputAtmosphericAwareWakedWindSpeed") is not None else False,
            "outputWakedTurbulenceIntensity": obj.get("outputWakedTurbulenceIntensity") if obj.get("outputWakedTurbulenceIntensity") is not None else False,
            "outputPowerOutput": obj.get("outputPowerOutput") if obj.get("outputPowerOutput") is not None else False,
            "outputAtmosphericAwarePowerOutput": obj.get("outputAtmosphericAwarePowerOutput") if obj.get("outputAtmosphericAwarePowerOutput") is not None else False,
            "outputProbabilityDistribution": obj.get("outputProbabilityDistribution") if obj.get("outputProbabilityDistribution") is not None else False,
            "outputUpstreamTurbineCausingWake": obj.get("outputUpstreamTurbineCausingWake") if obj.get("outputUpstreamTurbineCausingWake") is not None else False,
            "outputOperationalMode": obj.get("outputOperationalMode") if obj.get("outputOperationalMode") is not None else False,
            "localTurbineWindSpeedsOutputSettings": TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings.from_dict(obj["localTurbineWindSpeedsOutputSettings"]) if obj.get("localTurbineWindSpeedsOutputSettings") is not None else None
        })
        return _obj


