# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbinePerformance(BaseModel):
    """
    Performance data for turbine.
    """ # noqa: E501
    wind_speed_m_per_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The wind speed. Units: m/s", alias="windSpeed_m_per_s")
    power_output_k_w: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The power output. Units: kilo watts", alias="powerOutput_kW")
    thrust_coefficient: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The thrust coefficient.", alias="thrustCoefficient")
    frequency_pc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The probability of this wind speed occurring. Units: %.")
    __properties: ClassVar[List[str]] = ["windSpeed_m_per_s", "powerOutput_kW", "thrustCoefficient", "frequency_pc"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbinePerformance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbinePerformance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "windSpeed_m_per_s": obj.get("windSpeed_m_per_s"),
            "powerOutput_kW": obj.get("powerOutput_kW"),
            "thrustCoefficient": obj.get("thrustCoefficient"),
            "frequency_pc": obj.get("frequency_pc")
        })
        return _obj


