# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineManagementRule(BaseModel):
    """
    Data for one turbine management rule The rule is that the turbine will be in active mode when the different conditions are met
    """ # noqa: E501
    wind_direction_from: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The minimum wind direction that the rule applies to.", alias="windDirectionFrom")
    wind_direction_to: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The maximum wind direction that the rule applies to.", alias="windDirectionTo")
    minimum_wind_speed_m_per_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The minimum wind speed that the rule applies to.", alias="minimumWindSpeed_m_per_s")
    maximum_wind_speed_m_per_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The maximum wind speed that the rule applies to.", alias="maximumWindSpeed_m_per_s")
    time_from_as_time_of_day: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The start time of a daily time range specified as an absolute time of day.", alias="timeFromAsTimeOfDay")
    time_to_as_time_of_day: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The end time of daily time range specified as an absolute time of day.", alias="timeToAsTimeOfDay")
    time_from_as_sun_rise_offset: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The start time of a daily time range specified as an offset from sunrise. A +ve offset means after sunrise while a -ve means before sunrise.", alias="timeFromAsSunRiseOffset")
    time_to_as_sun_rise_offset: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The end time of a daily time range specified as an offset from sunrise. A +ve offset means after sunrise while a -ve means before sunrise.", alias="timeToAsSunRiseOffset")
    time_from_as_sun_set_offset: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The start time of a daily time range specified as an offset from sunset. A +ve offset means after sunset while a -ve means before sunset.", alias="timeFromAsSunSetOffset")
    time_to_as_sun_set_offset: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The end time of a daily time range specified as offset from sunset. A +ve offset means after sunset while a -ve means before sunset.", alias="timeToAsSunSetOffset")
    start_day_of_year: Optional[StrictInt] = Field(default=None, description="The start day of year that the rule applies to, inclusive. Assumes non leap year.", alias="startDayOfYear")
    end_day_of_year: Optional[StrictInt] = Field(default=None, description="The end day of year that the rule applies to, inclusive. Assumes non leap year. Note: if day 59 (28th of Feb) is specified, the calculation will interpret this as till the end of February which means that if a time series has records on the 29th of Feb these be included in this interval.", alias="endDayOfYear")
    minimum_temperature_degrees_celsius: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The minimum temperature that the rule applies to in celsius.", alias="minimumTemperature_degrees_celsius")
    maximum_temperature_degrees_celsius: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The maximum temperature that the rule applies to in celsius.", alias="maximumTemperature_degrees_celsius")
    active_mode: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Active mode for the turbine. If shutdown, value should be \"ShutDown\".", alias="activeMode")
    __properties: ClassVar[List[str]] = ["windDirectionFrom", "windDirectionTo", "minimumWindSpeed_m_per_s", "maximumWindSpeed_m_per_s", "timeFromAsTimeOfDay", "timeToAsTimeOfDay", "timeFromAsSunRiseOffset", "timeToAsSunRiseOffset", "timeFromAsSunSetOffset", "timeToAsSunSetOffset", "startDayOfYear", "endDayOfYear", "minimumTemperature_degrees_celsius", "maximumTemperature_degrees_celsius", "activeMode"]

    @field_validator('time_from_as_time_of_day', mode="before")
    def time_from_as_time_of_day_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    @field_validator('time_to_as_time_of_day', mode="before")
    def time_to_as_time_of_day_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    @field_validator('time_from_as_sun_rise_offset', mode="before")
    def time_from_as_sun_rise_offset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    @field_validator('time_to_as_sun_rise_offset', mode="before")
    def time_to_as_sun_rise_offset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    @field_validator('time_from_as_sun_set_offset', mode="before")
    def time_from_as_sun_set_offset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    @field_validator('time_to_as_sun_set_offset', mode="before")
    def time_to_as_sun_set_offset_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$", value):
            raise ValueError(r"must validate the regular expression /^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineManagementRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if time_from_as_time_of_day (nullable) is None
        # and model_fields_set contains the field
        if self.time_from_as_time_of_day is None and "time_from_as_time_of_day" in self.model_fields_set:
            _dict['timeFromAsTimeOfDay'] = None

        # set to None if time_to_as_time_of_day (nullable) is None
        # and model_fields_set contains the field
        if self.time_to_as_time_of_day is None and "time_to_as_time_of_day" in self.model_fields_set:
            _dict['timeToAsTimeOfDay'] = None

        # set to None if time_from_as_sun_rise_offset (nullable) is None
        # and model_fields_set contains the field
        if self.time_from_as_sun_rise_offset is None and "time_from_as_sun_rise_offset" in self.model_fields_set:
            _dict['timeFromAsSunRiseOffset'] = None

        # set to None if time_to_as_sun_rise_offset (nullable) is None
        # and model_fields_set contains the field
        if self.time_to_as_sun_rise_offset is None and "time_to_as_sun_rise_offset" in self.model_fields_set:
            _dict['timeToAsSunRiseOffset'] = None

        # set to None if time_from_as_sun_set_offset (nullable) is None
        # and model_fields_set contains the field
        if self.time_from_as_sun_set_offset is None and "time_from_as_sun_set_offset" in self.model_fields_set:
            _dict['timeFromAsSunSetOffset'] = None

        # set to None if time_to_as_sun_set_offset (nullable) is None
        # and model_fields_set contains the field
        if self.time_to_as_sun_set_offset is None and "time_to_as_sun_set_offset" in self.model_fields_set:
            _dict['timeToAsSunSetOffset'] = None

        # set to None if active_mode (nullable) is None
        # and model_fields_set contains the field
        if self.active_mode is None and "active_mode" in self.model_fields_set:
            _dict['activeMode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineManagementRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "windDirectionFrom": obj.get("windDirectionFrom"),
            "windDirectionTo": obj.get("windDirectionTo"),
            "minimumWindSpeed_m_per_s": obj.get("minimumWindSpeed_m_per_s"),
            "maximumWindSpeed_m_per_s": obj.get("maximumWindSpeed_m_per_s"),
            "timeFromAsTimeOfDay": obj.get("timeFromAsTimeOfDay"),
            "timeToAsTimeOfDay": obj.get("timeToAsTimeOfDay"),
            "timeFromAsSunRiseOffset": obj.get("timeFromAsSunRiseOffset"),
            "timeToAsSunRiseOffset": obj.get("timeToAsSunRiseOffset"),
            "timeFromAsSunSetOffset": obj.get("timeFromAsSunSetOffset"),
            "timeToAsSunSetOffset": obj.get("timeToAsSunSetOffset"),
            "startDayOfYear": obj.get("startDayOfYear"),
            "endDayOfYear": obj.get("endDayOfYear"),
            "minimumTemperature_degrees_celsius": obj.get("minimumTemperature_degrees_celsius"),
            "maximumTemperature_degrees_celsius": obj.get("maximumTemperature_degrees_celsius"),
            "activeMode": obj.get("activeMode")
        })
        return _obj


