# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineFlowAndPerformanceMatrix(BaseModel):
    """
    The turbine flow and performance matrix data for one turbine.
    """ # noqa: E501
    turbine_name: Optional[StrictStr] = Field(default=None, description="The turbine name.", alias="turbineName")
    wind_farm_name: Optional[StrictStr] = Field(default=None, description="The wind farm name.", alias="windFarmName")
    direction_for_first_bin_centre_degrees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The direction of the first direction bin. Units: degrees", alias="directionForFirstBinCentre_degrees")
    bin_center_wind_speeds_at_mast_m_per_s: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="The bin center wind speeds at the associated mast. Units: m/s", alias="binCenterWindSpeedsAtMast_m_per_s")
    ambient_wind_speed_m_per_s: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is turbine ambient wind speed at each mast wind speed. Units: m/s", alias="ambientWindSpeed_m_per_s")
    ambient_turbulence_intensity_percentage: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is turbine ambient wind speed at each mast wind speed. Units: percent", alias="ambientTurbulenceIntensity_percentage")
    dominant_wake_center_line_wind_speed_m_per_s: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is dominant wake center-line wind speed at each mast wind speed.", alias="dominantWakeCenterLineWindSpeed_m_per_s")
    dominant_wake_width: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is dominant wake width at each mast wind speed.", alias="dominantWakeWidth")
    dominant_wake_offset_m: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is dominant wake offset at each mast wind speed. Units: m", alias="dominantWakeOffset_m")
    waked_wind_speed_m_per_s: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is wake adjusted wind speed at each mast wind speed. Units: m/s", alias="wakedWindSpeed_m_per_s")
    atmospheric_condition_aware_waked_wind_speed_m_per_s: Optional[Dict[str, List[List[Union[StrictFloat, StrictInt]]]]] = Field(default=None, description="Dict keys are atmosphericConditionClassIds Outer List is direction sectors. Inner List is wake adjusted wind speed at each mast wind speed for the given atmospheric condition class. Units: m/s", alias="atmosphericConditionAwareWakedWindSpeed_m_per_s")
    waked_turbulence_intensity_percentage: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is wake adjusted turbulence intensity at each mast wind speed. Units: percent", alias="wakedTurbulenceIntensity_percentage")
    spot_power_output_w: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is turbine power output at each mast wind speed. Units: W", alias="spotPowerOutput_W")
    atmospheric_condition_aware_spot_power_output_w: Optional[Dict[str, List[Any]]] = Field(default=None, description="Dict keys are atmosphericConditionClassIds Outer List is direction sectors. Inner List is turbine power output at each mast wind speed for the given atmospheric condition class. Units: W", alias="atmosphericConditionAwareSpotPowerOutput_W")
    bin_power_output_w: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is direction sectors. Inner List is turbine power output representative of the wind speed bin. Units: W", alias="binPowerOutput_W")
    probability_distribution: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(default=None, description="Outer List is the direction sectors. Inner List is the turbine probability distribution at each mast wind speed.", alias="probabilityDistribution")
    upstream_turbine_causing_wake: Optional[List[List[StrictStr]]] = Field(default=None, description="Outer list is direction sectors. Inner list is the name of the upstream turbine that causes the wake.", alias="upstreamTurbineCausingWake")
    turbine_operational_mode: Optional[List[List[StrictStr]]] = Field(default=None, description="Outer list is direction sectors. Inner list is the turbine active mode at each mast wind speed.", alias="turbineOperationalMode")
    mast_to_turbine_speed_up: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Gets or sets the mast to turbine speed up.", alias="mastToTurbineSpeedUp")
    __properties: ClassVar[List[str]] = ["turbineName", "windFarmName", "directionForFirstBinCentre_degrees", "binCenterWindSpeedsAtMast_m_per_s", "ambientWindSpeed_m_per_s", "ambientTurbulenceIntensity_percentage", "dominantWakeCenterLineWindSpeed_m_per_s", "dominantWakeWidth", "dominantWakeOffset_m", "wakedWindSpeed_m_per_s", "atmosphericConditionAwareWakedWindSpeed_m_per_s", "wakedTurbulenceIntensity_percentage", "spotPowerOutput_W", "atmosphericConditionAwareSpotPowerOutput_W", "binPowerOutput_W", "probabilityDistribution", "upstreamTurbineCausingWake", "turbineOperationalMode", "mastToTurbineSpeedUp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrix from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if turbine_name (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_name is None and "turbine_name" in self.model_fields_set:
            _dict['turbineName'] = None

        # set to None if wind_farm_name (nullable) is None
        # and model_fields_set contains the field
        if self.wind_farm_name is None and "wind_farm_name" in self.model_fields_set:
            _dict['windFarmName'] = None

        # set to None if bin_center_wind_speeds_at_mast_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.bin_center_wind_speeds_at_mast_m_per_s is None and "bin_center_wind_speeds_at_mast_m_per_s" in self.model_fields_set:
            _dict['binCenterWindSpeedsAtMast_m_per_s'] = None

        # set to None if ambient_wind_speed_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.ambient_wind_speed_m_per_s is None and "ambient_wind_speed_m_per_s" in self.model_fields_set:
            _dict['ambientWindSpeed_m_per_s'] = None

        # set to None if ambient_turbulence_intensity_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.ambient_turbulence_intensity_percentage is None and "ambient_turbulence_intensity_percentage" in self.model_fields_set:
            _dict['ambientTurbulenceIntensity_percentage'] = None

        # set to None if dominant_wake_center_line_wind_speed_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.dominant_wake_center_line_wind_speed_m_per_s is None and "dominant_wake_center_line_wind_speed_m_per_s" in self.model_fields_set:
            _dict['dominantWakeCenterLineWindSpeed_m_per_s'] = None

        # set to None if dominant_wake_width (nullable) is None
        # and model_fields_set contains the field
        if self.dominant_wake_width is None and "dominant_wake_width" in self.model_fields_set:
            _dict['dominantWakeWidth'] = None

        # set to None if dominant_wake_offset_m (nullable) is None
        # and model_fields_set contains the field
        if self.dominant_wake_offset_m is None and "dominant_wake_offset_m" in self.model_fields_set:
            _dict['dominantWakeOffset_m'] = None

        # set to None if waked_wind_speed_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.waked_wind_speed_m_per_s is None and "waked_wind_speed_m_per_s" in self.model_fields_set:
            _dict['wakedWindSpeed_m_per_s'] = None

        # set to None if atmospheric_condition_aware_waked_wind_speed_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.atmospheric_condition_aware_waked_wind_speed_m_per_s is None and "atmospheric_condition_aware_waked_wind_speed_m_per_s" in self.model_fields_set:
            _dict['atmosphericConditionAwareWakedWindSpeed_m_per_s'] = None

        # set to None if waked_turbulence_intensity_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.waked_turbulence_intensity_percentage is None and "waked_turbulence_intensity_percentage" in self.model_fields_set:
            _dict['wakedTurbulenceIntensity_percentage'] = None

        # set to None if spot_power_output_w (nullable) is None
        # and model_fields_set contains the field
        if self.spot_power_output_w is None and "spot_power_output_w" in self.model_fields_set:
            _dict['spotPowerOutput_W'] = None

        # set to None if atmospheric_condition_aware_spot_power_output_w (nullable) is None
        # and model_fields_set contains the field
        if self.atmospheric_condition_aware_spot_power_output_w is None and "atmospheric_condition_aware_spot_power_output_w" in self.model_fields_set:
            _dict['atmosphericConditionAwareSpotPowerOutput_W'] = None

        # set to None if bin_power_output_w (nullable) is None
        # and model_fields_set contains the field
        if self.bin_power_output_w is None and "bin_power_output_w" in self.model_fields_set:
            _dict['binPowerOutput_W'] = None

        # set to None if probability_distribution (nullable) is None
        # and model_fields_set contains the field
        if self.probability_distribution is None and "probability_distribution" in self.model_fields_set:
            _dict['probabilityDistribution'] = None

        # set to None if upstream_turbine_causing_wake (nullable) is None
        # and model_fields_set contains the field
        if self.upstream_turbine_causing_wake is None and "upstream_turbine_causing_wake" in self.model_fields_set:
            _dict['upstreamTurbineCausingWake'] = None

        # set to None if turbine_operational_mode (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_operational_mode is None and "turbine_operational_mode" in self.model_fields_set:
            _dict['turbineOperationalMode'] = None

        # set to None if mast_to_turbine_speed_up (nullable) is None
        # and model_fields_set contains the field
        if self.mast_to_turbine_speed_up is None and "mast_to_turbine_speed_up" in self.model_fields_set:
            _dict['mastToTurbineSpeedUp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineFlowAndPerformanceMatrix from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "turbineName": obj.get("turbineName"),
            "windFarmName": obj.get("windFarmName"),
            "directionForFirstBinCentre_degrees": obj.get("directionForFirstBinCentre_degrees"),
            "binCenterWindSpeedsAtMast_m_per_s": obj.get("binCenterWindSpeedsAtMast_m_per_s"),
            "ambientWindSpeed_m_per_s": obj.get("ambientWindSpeed_m_per_s"),
            "ambientTurbulenceIntensity_percentage": obj.get("ambientTurbulenceIntensity_percentage"),
            "dominantWakeCenterLineWindSpeed_m_per_s": obj.get("dominantWakeCenterLineWindSpeed_m_per_s"),
            "dominantWakeWidth": obj.get("dominantWakeWidth"),
            "dominantWakeOffset_m": obj.get("dominantWakeOffset_m"),
            "wakedWindSpeed_m_per_s": obj.get("wakedWindSpeed_m_per_s"),
            "atmosphericConditionAwareWakedWindSpeed_m_per_s": obj.get("atmosphericConditionAwareWakedWindSpeed_m_per_s"),
            "wakedTurbulenceIntensity_percentage": obj.get("wakedTurbulenceIntensity_percentage"),
            "spotPowerOutput_W": obj.get("spotPowerOutput_W"),
            "atmosphericConditionAwareSpotPowerOutput_W": obj.get("atmosphericConditionAwareSpotPowerOutput_W"),
            "binPowerOutput_W": obj.get("binPowerOutput_W"),
            "probabilityDistribution": obj.get("probabilityDistribution"),
            "upstreamTurbineCausingWake": obj.get("upstreamTurbineCausingWake"),
            "turbineOperationalMode": obj.get("turbineOperationalMode"),
            "mastToTurbineSpeedUp": obj.get("mastToTurbineSpeedUp")
        })
        return _obj


