# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.sensitivity_curve_entry import SensitivityCurveEntry
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineSensitivityCurve(BaseModel):
    """
    A class for holding a wind climate sensitivity curve.
    """ # noqa: E501
    wind_farm: Optional[StrictStr] = Field(default=None, description="Gets or sets the wind farm name", alias="windFarm")
    turbine: Optional[StrictStr] = Field(default=None, description="Gets or sets the turbine name")
    entries: Optional[List[SensitivityCurveEntry]] = Field(default=None, description="Gets or sets the Entries")
    __properties: ClassVar[List[str]] = ["windFarm", "turbine", "entries"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineSensitivityCurve from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entries (list)
        _items = []
        if self.entries:
            for _item_entries in self.entries:
                _items.append(_item_entries.to_dict() if _item_entries is not None else None)
            _dict['entries'] = _items
        # set to None if wind_farm (nullable) is None
        # and model_fields_set contains the field
        if self.wind_farm is None and "wind_farm" in self.model_fields_set:
            _dict['windFarm'] = None

        # set to None if turbine (nullable) is None
        # and model_fields_set contains the field
        if self.turbine is None and "turbine" in self.model_fields_set:
            _dict['turbine'] = None

        # set to None if entries (nullable) is None
        # and model_fields_set contains the field
        if self.entries is None and "entries" in self.model_fields_set:
            _dict['entries'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineSensitivityCurve from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "windFarm": obj.get("windFarm"),
            "turbine": obj.get("turbine"),
            "entries": [SensitivityCurveEntry.from_dict(_item) for _item in obj["entries"]] if obj.get("entries") is not None else None
        })
        return _obj


