# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineLocation(BaseModel):
    """
    The turbine position and dimensions.
    """ # noqa: E501
    easting_m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The East position of the turbine. Units: m.")
    northing_m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The North position of the turbine. Units: m.")
    hub_height_m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The hub height of the turbine. Units: m.", alias="hubHeight_m")
    rotor_diameter_m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The rotor diameter. Units: m.", alias="rotorDiameter_m")
    __properties: ClassVar[List[str]] = ["easting_m", "northing_m", "hubHeight_m", "rotorDiameter_m"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "easting_m": obj.get("easting_m"),
            "northing_m": obj.get("northing_m"),
            "hubHeight_m": obj.get("hubHeight_m"),
            "rotorDiameter_m": obj.get("rotorDiameter_m")
        })
        return _obj


