# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.location import Location
from dnv_windfarmer_client.models.turbine_management_rule import TurbineManagementRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Turbine(BaseModel):
    """
    Models the location where the wind turbine is placed.
    """ # noqa: E501
    name: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="The turbine name. Should be unique within a wind farm.")
    associated_wind_climate_id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="The id of the associated wind climate.", alias="associatedWindClimateId")
    turbine_model_id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="The unique id of the turbine model.", alias="turbineModelId")
    is_installed: Optional[StrictBool] = Field(default=None, description="Whether the turbine is installed or not.", alias="isInstalled")
    production_yield: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, description="The yield of the turbine. Units: MWh/year.", alias="productionYield")
    confidence_weighting: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, description="The confidence weighting of rge ProductionYield.", alias="confidenceWeighting")
    location: Location = Field(description="The location of the turbine.")
    curtailment_rules: Optional[List[TurbineManagementRule]] = Field(default=None, description="The turbine management rules for the turbine.", alias="curtailmentRules")
    park_wake_decay_constant: Optional[Union[StrictFloat, StrictInt]] = Field(default=0.07, description="Specifies the decay constant at the turbine, only defined when used in the Park calculation.", alias="parkWakeDecayConstant")
    __properties: ClassVar[List[str]] = ["name", "associatedWindClimateId", "turbineModelId", "isInstalled", "productionYield", "confidenceWeighting", "location", "curtailmentRules", "parkWakeDecayConstant"]

    @field_validator('name', mode="before")
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[^@]*$", value):
            raise ValueError(r"must validate the regular expression /^[^@]*$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Turbine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in curtailment_rules (list)
        _items = []
        if self.curtailment_rules:
            for _item_curtailment_rules in self.curtailment_rules:
                _items.append(_item_curtailment_rules.to_dict() if _item_curtailment_rules is not None else None)
            _dict['curtailmentRules'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if associated_wind_climate_id (nullable) is None
        # and model_fields_set contains the field
        if self.associated_wind_climate_id is None and "associated_wind_climate_id" in self.model_fields_set:
            _dict['associatedWindClimateId'] = None

        # set to None if turbine_model_id (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_model_id is None and "turbine_model_id" in self.model_fields_set:
            _dict['turbineModelId'] = None

        # set to None if curtailment_rules (nullable) is None
        # and model_fields_set contains the field
        if self.curtailment_rules is None and "curtailment_rules" in self.model_fields_set:
            _dict['curtailmentRules'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Turbine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "associatedWindClimateId": obj.get("associatedWindClimateId"),
            "turbineModelId": obj.get("turbineModelId"),
            "isInstalled": obj.get("isInstalled"),
            "productionYield": obj.get("productionYield") if obj.get("productionYield") is not None else 0,
            "confidenceWeighting": obj.get("confidenceWeighting") if obj.get("confidenceWeighting") is not None else 0,
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "curtailmentRules": [TurbineManagementRule.from_dict(_item) for _item in obj["curtailmentRules"]] if obj.get("curtailmentRules") is not None else None,
            "parkWakeDecayConstant": obj.get("parkWakeDecayConstant") if obj.get("parkWakeDecayConstant") is not None else 0.07
        })
        return _obj


