# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.turbine_model_performance_data_point import TurbineModelPerformanceDataPoint
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TurbineModelPerformance(BaseModel):
    """
    Defines a turbine model power curve for a specific mode, air density etc.
    """ # noqa: E501
    turbine_operational_mode: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="The turbine mode, defaults to normal.", alias="turbineOperationalMode")
    adjusted_high_speed_cut_out_m_per_s: Union[StrictFloat, StrictInt] = Field(description="The high wind speed cut out, adjusted to model the hysteresis effect.  Units: m/s", alias="adjustedHighSpeedCutOut_m_per_s")
    adjusted_low_speed_cut_in_m_per_s: Union[StrictFloat, StrictInt] = Field(description="The low speed cut in, adjusted to model the hysteresis effect. Units: m/s", alias="adjustedLowSpeedCutIn_m_per_s")
    low_speed_cut_in_m_per_s: Union[StrictFloat, StrictInt] = Field(description="The low wind speed cut in.  Units: m/s", alias="lowSpeedCutIn_m_per_s")
    high_speed_cut_out_m_per_s: Union[StrictFloat, StrictInt] = Field(description="The high wind speed cut out.  Units: m/s", alias="highSpeedCutOut_m_per_s")
    turbulence_intensity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The turbulence intensity. Meta data only, not used in calculations Units: percent", alias="turbulenceIntensity")
    air_density_kg_per_m3: Union[StrictFloat, StrictInt] = Field(description="The air density.  Units: kg/m3", alias="airDensity_kg_per_m3")
    temperature_deg_c: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The temperature.  Units: Deg C", alias="temperature_deg_C")
    yaw_misalignment_degrees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The yaw misalignment.  Units: degrees", alias="yawMisalignment_degrees")
    power_derating_delta_k_w: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The power derating delta.  Units: kW", alias="powerDeratingDelta_kW")
    performance_data_points: Optional[List[TurbineModelPerformanceDataPoint]] = Field(description="The performance specific data.", alias="performanceDataPoints")
    __properties: ClassVar[List[str]] = ["turbineOperationalMode", "adjustedHighSpeedCutOut_m_per_s", "adjustedLowSpeedCutIn_m_per_s", "lowSpeedCutIn_m_per_s", "highSpeedCutOut_m_per_s", "turbulenceIntensity", "airDensity_kg_per_m3", "temperature_deg_C", "yawMisalignment_degrees", "powerDeratingDelta_kW", "performanceDataPoints"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurbineModelPerformance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in performance_data_points (list)
        _items = []
        if self.performance_data_points:
            for _item_performance_data_points in self.performance_data_points:
                _items.append(_item_performance_data_points.to_dict() if _item_performance_data_points is not None else None)
            _dict['performanceDataPoints'] = _items
        # set to None if turbine_operational_mode (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_operational_mode is None and "turbine_operational_mode" in self.model_fields_set:
            _dict['turbineOperationalMode'] = None

        # set to None if performance_data_points (nullable) is None
        # and model_fields_set contains the field
        if self.performance_data_points is None and "performance_data_points" in self.model_fields_set:
            _dict['performanceDataPoints'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurbineModelPerformance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "turbineOperationalMode": obj.get("turbineOperationalMode") if "turbineOperationalMode" in obj else 'normal',
            "adjustedHighSpeedCutOut_m_per_s": obj.get("adjustedHighSpeedCutOut_m_per_s"),
            "adjustedLowSpeedCutIn_m_per_s": obj.get("adjustedLowSpeedCutIn_m_per_s"),
            "lowSpeedCutIn_m_per_s": obj.get("lowSpeedCutIn_m_per_s"),
            "highSpeedCutOut_m_per_s": obj.get("highSpeedCutOut_m_per_s"),
            "turbulenceIntensity": obj.get("turbulenceIntensity"),
            "airDensity_kg_per_m3": obj.get("airDensity_kg_per_m3"),
            "temperature_deg_C": obj.get("temperature_deg_C"),
            "yawMisalignment_degrees": obj.get("yawMisalignment_degrees"),
            "powerDeratingDelta_kW": obj.get("powerDeratingDelta_kW"),
            "performanceDataPoints": [TurbineModelPerformanceDataPoint.from_dict(_item) for _item in obj["performanceDataPoints"]] if obj.get("performanceDataPoints") is not None else None
        })
        return _obj


