# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WakeModelType(str, Enum):
    """
    The type of wake calculation model
    """

    """
    allowed enum values
    """
    MODIFIEDPARK = 'ModifiedPark'
    EDDYVISCOSITY = 'EddyViscosity'
    TURBOPARK = 'TurbOPark'
    CFDML = 'CFDML'
    NOWAKEMODEL = 'NoWakeModel'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WakeModelType from a JSON string"""
        return cls(json.loads(json_str))


