# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.cfdml import Cfdml
from dnv_windfarmer_client.models.eddy_viscosity import EddyViscosity
from dnv_windfarmer_client.models.modified_park import ModifiedPark
from dnv_windfarmer_client.models.no_wake_model import NoWakeModel
from dnv_windfarmer_client.models.turb_o_park import TurbOPark
from dnv_windfarmer_client.models.wake_model_type import WakeModelType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WakeModelSettings(BaseModel):
    """
    The wake model settings.
    """ # noqa: E501
    wake_model_type: Optional[WakeModelType] = Field(default=None, description="Wake model to use. If NoWakeModel the gross power will be provided.", alias="wakeModelType")
    eddy_viscosity: Optional[EddyViscosity] = Field(default=None, description="The Eddy Viscosity wake model settings. Can be omited if WakeModelType is not EddyViscosity.", alias="eddyViscosity")
    modified_park: Optional[ModifiedPark] = Field(default=None, description="The Modified Park wake model settings. Can be omited if WakeModelType is not ModifiedPark.", alias="modifiedPark")
    turb_o_park: Optional[TurbOPark] = Field(default=None, description="The TurbOPark wake model settings.  Can be omited if WakeModelType is not TurbOPark.", alias="turbOPark")
    cfdml: Optional[Cfdml] = Field(default=None, description="The CFD.ML wake model settings. Can be omited if WakeModelType is not CFDML.")
    no_wake_model: Optional[NoWakeModel] = Field(default=None, description="No Wake model settings. Can be omited if WakeModelType is not NoWakeModel.", alias="noWakeModel")
    __properties: ClassVar[List[str]] = ["wakeModelType", "eddyViscosity", "modifiedPark", "turbOPark", "cfdml", "noWakeModel"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WakeModelSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of eddy_viscosity
        if self.eddy_viscosity:
            _dict['eddyViscosity'] = self.eddy_viscosity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified_park
        if self.modified_park:
            _dict['modifiedPark'] = self.modified_park.to_dict()
        # override the default output from pydantic by calling `to_dict()` of turb_o_park
        if self.turb_o_park:
            _dict['turbOPark'] = self.turb_o_park.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cfdml
        if self.cfdml:
            _dict['cfdml'] = self.cfdml.to_dict()
        # override the default output from pydantic by calling `to_dict()` of no_wake_model
        if self.no_wake_model:
            _dict['noWakeModel'] = self.no_wake_model.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WakeModelSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "wakeModelType": obj.get("wakeModelType"),
            "eddyViscosity": EddyViscosity.from_dict(obj["eddyViscosity"]) if obj.get("eddyViscosity") is not None else None,
            "modifiedPark": ModifiedPark.from_dict(obj["modifiedPark"]) if obj.get("modifiedPark") is not None else None,
            "turbOPark": TurbOPark.from_dict(obj["turbOPark"]) if obj.get("turbOPark") is not None else None,
            "cfdml": Cfdml.from_dict(obj["cfdml"]) if obj.get("cfdml") is not None else None,
            "noWakeModel": NoWakeModel.from_dict(obj["noWakeModel"]) if obj.get("noWakeModel") is not None else None
        })
        return _obj


