# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.location import Location
from dnv_windfarmer_client.models.weibull_sector_parameters import WeibullSectorParameters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WeibullWindClimate(BaseModel):
    """
    Weibull parameters describing the wind climate at a particular height and location
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="Unique id for the wind climate, typically the mast/turbine name plus the height above ground. Needs to be the same as property AssociatedWindClimateId in Turbine")
    location: Location = Field(description="The wind climate location: easting, northing and base height")
    height_above_ground_m: Union[StrictFloat, StrictInt] = Field(description="The wind climate height above ground. Units: m", alias="heightAboveGround_m")
    number_of_direction_sectors: StrictInt = Field(description="The number of directions for which there is climate data.  Units: -", alias="numberOfDirectionSectors")
    direction_for_first_bin_centre_degrees: Union[StrictFloat, StrictInt] = Field(description="The wind direction of the first climate data point. Units: degrees", alias="directionForFirstBinCentre_degrees")
    sector_weibull_parameters: Optional[List[WeibullSectorParameters]] = Field(description="Weibull parameters for each sector. Length of list must be int WeibullWindClimate.NumberOfDirectionSectors and first element corresponds to direction double WeibullWindClimate.DirectionForFirstBinCentre Sum of all sectors probabilities should be 1.", alias="sectorWeibullParameters")
    turbulence_intensity: Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]] = Field(description="A flat turbulence intensity value. Units: ratio Note: This is a ratio not a percent.", alias="turbulenceIntensity")
    __properties: ClassVar[List[str]] = ["id", "location", "heightAboveGround_m", "numberOfDirectionSectors", "directionForFirstBinCentre_degrees", "sectorWeibullParameters", "turbulenceIntensity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WeibullWindClimate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sector_weibull_parameters (list)
        _items = []
        if self.sector_weibull_parameters:
            for _item_sector_weibull_parameters in self.sector_weibull_parameters:
                _items.append(_item_sector_weibull_parameters.to_dict() if _item_sector_weibull_parameters is not None else None)
            _dict['sectorWeibullParameters'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if sector_weibull_parameters (nullable) is None
        # and model_fields_set contains the field
        if self.sector_weibull_parameters is None and "sector_weibull_parameters" in self.model_fields_set:
            _dict['sectorWeibullParameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WeibullWindClimate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "heightAboveGround_m": obj.get("heightAboveGround_m"),
            "numberOfDirectionSectors": obj.get("numberOfDirectionSectors"),
            "directionForFirstBinCentre_degrees": obj.get("directionForFirstBinCentre_degrees"),
            "sectorWeibullParameters": [WeibullSectorParameters.from_dict(_item) for _item in obj["sectorWeibullParameters"]] if obj.get("sectorWeibullParameters") is not None else None,
            "turbulenceIntensity": obj.get("turbulenceIntensity")
        })
        return _obj


