# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.cfdml_training_set_alignment_metrics import CfdmlTrainingSetAlignmentMetrics
from dnv_windfarmer_client.models.turbine_blockage_efficiency import TurbineBlockageEfficiency
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WeightedCfdmlIntermediateData(BaseModel):
    """
    WeightedCfdmlIntermediateData
    """ # noqa: E501
    intermediate_cfdml_v2_data: Optional[Dict[str, Dict[str, Dict[str, List[TurbineBlockageEfficiency]]]]] = Field(default=None, description="The per-flowcase, per-turbine blockage efficiencies for the CFDML V2 model.", alias="intermediateCfdmlV2Data")
    intermediate_cfdml_v1_data: Optional[Dict[str, Dict[str, List[TurbineBlockageEfficiency]]]] = Field(default=None, description="The per-flowcase, per-turbine blockage efficiencies for the CFDML V1 model.", alias="intermediateCfdmlV1Data")
    training_set_alignment_metrics: Optional[CfdmlTrainingSetAlignmentMetrics] = Field(default=None, description="The training set alignment metrics.", alias="trainingSetAlignmentMetrics")
    __properties: ClassVar[List[str]] = ["intermediateCfdmlV2Data", "intermediateCfdmlV1Data", "trainingSetAlignmentMetrics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WeightedCfdmlIntermediateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in intermediate_cfdml_v1_data (dict of dict)
        _field_dict_of_dict = {}
        if self.intermediate_cfdml_v1_data:
            for _key_intermediate_cfdml_v1_data, _value_intermediate_cfdml_v1_data in self.intermediate_cfdml_v1_data.items():
                _field_dict_of_dict[_key_intermediate_cfdml_v1_data] = {
                    _key: _value.to_dict() if _value is not None else None for _key, _value in _value_intermediate_cfdml_v1_data.items()
                } if _value_intermediate_cfdml_v1_data is not None else None
            _dict['intermediateCfdmlV1Data'] = _field_dict_of_dict
        # override the default output from pydantic by calling `to_dict()` of training_set_alignment_metrics
        if self.training_set_alignment_metrics:
            _dict['trainingSetAlignmentMetrics'] = self.training_set_alignment_metrics.to_dict()
        # set to None if intermediate_cfdml_v2_data (nullable) is None
        # and model_fields_set contains the field
        if self.intermediate_cfdml_v2_data is None and "intermediate_cfdml_v2_data" in self.model_fields_set:
            _dict['intermediateCfdmlV2Data'] = None

        # set to None if intermediate_cfdml_v1_data (nullable) is None
        # and model_fields_set contains the field
        if self.intermediate_cfdml_v1_data is None and "intermediate_cfdml_v1_data" in self.model_fields_set:
            _dict['intermediateCfdmlV1Data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WeightedCfdmlIntermediateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "intermediateCfdmlV2Data": obj.get("intermediateCfdmlV2Data"),
            "intermediateCfdmlV1Data": obj.get("intermediateCfdmlV1Data"),
            "trainingSetAlignmentMetrics": CfdmlTrainingSetAlignmentMetrics.from_dict(obj["trainingSetAlignmentMetrics"]) if obj.get("trainingSetAlignmentMetrics") is not None else None
        })
        return _obj


