# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dnv_windfarmer_client.models.intermediate_beet_run import IntermediateBeetRun
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WeightedBeetIntermediateData(BaseModel):
    """
    The weighted blockage model intermediate result data.
    """ # noqa: E501
    wind_farm_name: Optional[List[StrictStr]] = Field(default=None, description="Gets or sets the used windFarms.", alias="windFarmName")
    intermediate_blockage_run: Optional[List[IntermediateBeetRun]] = Field(default=None, description="An intermediate blockage run.", alias="intermediateBlockageRun")
    __properties: ClassVar[List[str]] = ["windFarmName", "intermediateBlockageRun"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WeightedBeetIntermediateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in intermediate_blockage_run (list)
        _items = []
        if self.intermediate_blockage_run:
            for _item_intermediate_blockage_run in self.intermediate_blockage_run:
                _items.append(_item_intermediate_blockage_run.to_dict() if _item_intermediate_blockage_run is not None else None)
            _dict['intermediateBlockageRun'] = _items
        # set to None if wind_farm_name (nullable) is None
        # and model_fields_set contains the field
        if self.wind_farm_name is None and "wind_farm_name" in self.model_fields_set:
            _dict['windFarmName'] = None

        # set to None if intermediate_blockage_run (nullable) is None
        # and model_fields_set contains the field
        if self.intermediate_blockage_run is None and "intermediate_blockage_run" in self.model_fields_set:
            _dict['intermediateBlockageRun'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WeightedBeetIntermediateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "windFarmName": obj.get("windFarmName"),
            "intermediateBlockageRun": [IntermediateBeetRun.from_dict(_item) for _item in obj["intermediateBlockageRun"]] if obj.get("intermediateBlockageRun") is not None else None
        })
        return _obj


