# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix import TurbineFlowAndPerformanceMatrix
from dnv_windfarmer_client.models.turbine_result import TurbineResult
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WindFarmAepOutput(BaseModel):
    """
    Annual energy production results for a wind farm.
    """ # noqa: E501
    wind_farm_name: Optional[StrictStr] = Field(default=None, description="The wind farm name.", alias="windFarmName")
    gross_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output assuming no blockage, no wake losses, no cut-out hysteresis and no curtailment. Units: MWh/yr", alias="grossAnnualEnergyYield_MWh_per_year")
    ideal_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The ideal energy yield. Units : MWh/yr", alias="idealAnnualEnergyYield_MWh_per_year")
    internal_blockage_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output including internal blockage efficiency, only different to BlockageOn variant for CFDML as a wake calculation.", alias="internalBlockageOnAnnualEnergyYield_MWh_per_year")
    blockage_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output assuming no wake losses, no cut-out hysteresis and no curtailment. Units: MWh/yr", alias="blockageOnAnnualEnergyYield_MWh_per_year")
    internal_wakes_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output including wake losses from this wind farm only, but with no large wind farm correction, no cut-out hysteresis and no curtailment. Units: MWh/yr", alias="internalWakesOnAnnualEnergyYield_MWh_per_year")
    hysteresis_adjustment_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output including wake losses from this wind farm only and cut-out hysteresis but no large wind farm correction and no curtailment. Units: MWh/yr", alias="hysteresisAdjustmentOnAnnualEnergyYield_MWh_per_year")
    large_wind_farm_correction_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output including wake losses from this wind farm only and cut-out hysteresis and including large wind farm correction but not curtailment. Units: MWh/yr", alias="largeWindFarmCorrectionOnAnnualEnergyYield_MWh_per_year")
    neighbors_wakes_on_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The energy output including wake losses from this and neighboring wind farms, and cut-out hysteresis, and including large wind farm correction but not curtailment. Units: MWh/yr", alias="neighborsWakesOnAnnualEnergyYield_MWh_per_year")
    full_annual_energy_yield_mwh_per_year: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The full anuual energy yield. Units: MWh/yr", alias="fullAnnualEnergyYield_MWh_per_year")
    turbine_results: Optional[List[TurbineResult]] = Field(default=None, description="Turbines on the wind farm.", alias="turbineResults")
    turbine_flow_and_performance_matrices_with_mast_binning: Optional[List[TurbineFlowAndPerformanceMatrix]] = Field(default=None, description="Flow and performance matrix data with mast reference wind speeds.", alias="turbineFlowAndPerformanceMatricesWithMastBinning")
    turbine_flow_and_performance_matrices_with_turbine_binning: Optional[List[TurbineFlowAndPerformanceMatrix]] = Field(default=None, description="Flow and performance matrix data with turbine local wind speeds.", alias="turbineFlowAndPerformanceMatricesWithTurbineBinning")
    __properties: ClassVar[List[str]] = ["windFarmName", "grossAnnualEnergyYield_MWh_per_year", "idealAnnualEnergyYield_MWh_per_year", "internalBlockageOnAnnualEnergyYield_MWh_per_year", "blockageOnAnnualEnergyYield_MWh_per_year", "internalWakesOnAnnualEnergyYield_MWh_per_year", "hysteresisAdjustmentOnAnnualEnergyYield_MWh_per_year", "largeWindFarmCorrectionOnAnnualEnergyYield_MWh_per_year", "neighborsWakesOnAnnualEnergyYield_MWh_per_year", "fullAnnualEnergyYield_MWh_per_year", "turbineResults", "turbineFlowAndPerformanceMatricesWithMastBinning", "turbineFlowAndPerformanceMatricesWithTurbineBinning"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WindFarmAepOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_results (list)
        _items = []
        if self.turbine_results:
            for _item_turbine_results in self.turbine_results:
                _items.append(_item_turbine_results.to_dict() if _item_turbine_results is not None else None)
            _dict['turbineResults'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_flow_and_performance_matrices_with_mast_binning (list)
        _items = []
        if self.turbine_flow_and_performance_matrices_with_mast_binning:
            for _item_turbine_flow_and_performance_matrices_with_mast_binning in self.turbine_flow_and_performance_matrices_with_mast_binning:
                _items.append(_item_turbine_flow_and_performance_matrices_with_mast_binning.to_dict() if _item_turbine_flow_and_performance_matrices_with_mast_binning is not None else None)
            _dict['turbineFlowAndPerformanceMatricesWithMastBinning'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in turbine_flow_and_performance_matrices_with_turbine_binning (list)
        _items = []
        if self.turbine_flow_and_performance_matrices_with_turbine_binning:
            for _item_turbine_flow_and_performance_matrices_with_turbine_binning in self.turbine_flow_and_performance_matrices_with_turbine_binning:
                _items.append(_item_turbine_flow_and_performance_matrices_with_turbine_binning.to_dict() if _item_turbine_flow_and_performance_matrices_with_turbine_binning is not None else None)
            _dict['turbineFlowAndPerformanceMatricesWithTurbineBinning'] = _items
        # set to None if wind_farm_name (nullable) is None
        # and model_fields_set contains the field
        if self.wind_farm_name is None and "wind_farm_name" in self.model_fields_set:
            _dict['windFarmName'] = None

        # set to None if turbine_results (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_results is None and "turbine_results" in self.model_fields_set:
            _dict['turbineResults'] = None

        # set to None if turbine_flow_and_performance_matrices_with_mast_binning (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_flow_and_performance_matrices_with_mast_binning is None and "turbine_flow_and_performance_matrices_with_mast_binning" in self.model_fields_set:
            _dict['turbineFlowAndPerformanceMatricesWithMastBinning'] = None

        # set to None if turbine_flow_and_performance_matrices_with_turbine_binning (nullable) is None
        # and model_fields_set contains the field
        if self.turbine_flow_and_performance_matrices_with_turbine_binning is None and "turbine_flow_and_performance_matrices_with_turbine_binning" in self.model_fields_set:
            _dict['turbineFlowAndPerformanceMatricesWithTurbineBinning'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WindFarmAepOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "windFarmName": obj.get("windFarmName"),
            "grossAnnualEnergyYield_MWh_per_year": obj.get("grossAnnualEnergyYield_MWh_per_year"),
            "idealAnnualEnergyYield_MWh_per_year": obj.get("idealAnnualEnergyYield_MWh_per_year"),
            "internalBlockageOnAnnualEnergyYield_MWh_per_year": obj.get("internalBlockageOnAnnualEnergyYield_MWh_per_year"),
            "blockageOnAnnualEnergyYield_MWh_per_year": obj.get("blockageOnAnnualEnergyYield_MWh_per_year"),
            "internalWakesOnAnnualEnergyYield_MWh_per_year": obj.get("internalWakesOnAnnualEnergyYield_MWh_per_year"),
            "hysteresisAdjustmentOnAnnualEnergyYield_MWh_per_year": obj.get("hysteresisAdjustmentOnAnnualEnergyYield_MWh_per_year"),
            "largeWindFarmCorrectionOnAnnualEnergyYield_MWh_per_year": obj.get("largeWindFarmCorrectionOnAnnualEnergyYield_MWh_per_year"),
            "neighborsWakesOnAnnualEnergyYield_MWh_per_year": obj.get("neighborsWakesOnAnnualEnergyYield_MWh_per_year"),
            "fullAnnualEnergyYield_MWh_per_year": obj.get("fullAnnualEnergyYield_MWh_per_year"),
            "turbineResults": [TurbineResult.from_dict(_item) for _item in obj["turbineResults"]] if obj.get("turbineResults") is not None else None,
            "turbineFlowAndPerformanceMatricesWithMastBinning": [TurbineFlowAndPerformanceMatrix.from_dict(_item) for _item in obj["turbineFlowAndPerformanceMatricesWithMastBinning"]] if obj.get("turbineFlowAndPerformanceMatricesWithMastBinning") is not None else None,
            "turbineFlowAndPerformanceMatricesWithTurbineBinning": [TurbineFlowAndPerformanceMatrix.from_dict(_item) for _item in obj["turbineFlowAndPerformanceMatricesWithTurbineBinning"]] if obj.get("turbineFlowAndPerformanceMatricesWithTurbineBinning") is not None else None
        })
        return _obj


