# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.location import Location
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WindClimate(BaseModel):
    """
    Data describing the wind climate at a particular elevation at a measurement location.
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(description="Unique id for the wind climate, typically the mast name plus the height above ground. Needs to be the same as property AssociatedWindClimateId in Turbine")
    location: Location = Field(description="The wind climate location: easting, northing and base height")
    height_above_ground_m: Union[StrictFloat, StrictInt] = Field(description="The wind climate height above ground. Units: m", alias="heightAboveGround_m")
    number_of_direction_sectors: StrictInt = Field(description="The number of directions for which there is climate data.  Units: -", alias="numberOfDirectionSectors")
    direction_for_first_bin_centre_degrees: Union[StrictFloat, StrictInt] = Field(description="The wind direction of the first climate data point. Units: degrees", alias="directionForFirstBinCentre_degrees")
    wind_speed_bin_upper_limits_m_per_s: Optional[List[Union[StrictFloat, StrictInt]]] = Field(description="The upper limit for each wind speed bin. It is assumed that the lower limit for each bin is the upper limit of the preceding bin, except for the first bin which is assumed to start at zero. Units: m/s", alias="windSpeedBinUpperLimits_m_per_s")
    probability_distribution: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(description="Outer List is direction sectors Inner List is probabilities at each wind speed.", alias="probabilityDistribution")
    turbulence_intensity: Optional[List[List[Union[StrictFloat, StrictInt]]]] = Field(description="Outer List is direction sectors Inner List is turbulence intensity at each wind speed TI = std deviation of wind speed / mean wind speed Note: This is a ratio not a percent.", alias="turbulenceIntensity")
    __properties: ClassVar[List[str]] = ["id", "location", "heightAboveGround_m", "numberOfDirectionSectors", "directionForFirstBinCentre_degrees", "windSpeedBinUpperLimits_m_per_s", "probabilityDistribution", "turbulenceIntensity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WindClimate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if wind_speed_bin_upper_limits_m_per_s (nullable) is None
        # and model_fields_set contains the field
        if self.wind_speed_bin_upper_limits_m_per_s is None and "wind_speed_bin_upper_limits_m_per_s" in self.model_fields_set:
            _dict['windSpeedBinUpperLimits_m_per_s'] = None

        # set to None if probability_distribution (nullable) is None
        # and model_fields_set contains the field
        if self.probability_distribution is None and "probability_distribution" in self.model_fields_set:
            _dict['probabilityDistribution'] = None

        # set to None if turbulence_intensity (nullable) is None
        # and model_fields_set contains the field
        if self.turbulence_intensity is None and "turbulence_intensity" in self.model_fields_set:
            _dict['turbulenceIntensity'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WindClimate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "heightAboveGround_m": obj.get("heightAboveGround_m"),
            "numberOfDirectionSectors": obj.get("numberOfDirectionSectors"),
            "directionForFirstBinCentre_degrees": obj.get("directionForFirstBinCentre_degrees"),
            "windSpeedBinUpperLimits_m_per_s": obj.get("windSpeedBinUpperLimits_m_per_s"),
            "probabilityDistribution": obj.get("probabilityDistribution"),
            "turbulenceIntensity": obj.get("turbulenceIntensity")
        })
        return _obj


