# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.comprehensive_site_classification import ComprehensiveSiteClassification

class TestComprehensiveSiteClassification(unittest.TestCase):
    """ComprehensiveSiteClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComprehensiveSiteClassification:
        """Test ComprehensiveSiteClassification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComprehensiveSiteClassification`
        """
        model = ComprehensiveSiteClassification()
        if include_optional:
            return ComprehensiveSiteClassification(
                metadata = dnv_windfarmer_client.models.metadata.Metadata(
                    site_latitude = 1.337, 
                    site_longitude = 1.337, 
                    nearest_era5_grid_latitude = 1.337, 
                    nearest_era5_grid_longitude = 1.337, 
                    distance_to_nearest_grid_point_km = 1.337, 
                    number_of_sectors = 56, 
                    coastline_detection_radius_km = 1.337, 
                    stability_classification_method = '', 
                    era5_time_series_start_date = '', 
                    era5_time_series_end_date = '', ),
                atmospheric_conditions = dnv_windfarmer_client.models.atmospheric_conditions.AtmosphericConditions(
                    atmospheric_condition_classes = [
                        dnv_windfarmer_client.models.atmospheric_condition_class.AtmosphericConditionClass(
                            id = '', 
                            boundary_layer_height_m = 1, 
                            lapse_rate_k_per_100m = 0, 
                            delta_theta_across_inversion_layer_k = 0, 
                            thickness_inversion_layer_m = 0, 
                            heights_above_surface_m = [
                                1.337
                                ], 
                            turbulence_intensity_profile = [
                                1.337
                                ], 
                            wind_speed_vertical_gradient_profile_per_s_m = [
                                1.337
                                ], )
                        ], 
                    atmospheric_condition_probability_distribution = [
                        dnv_windfarmer_client.models.atmospheric_condition_probability_sector.AtmosphericConditionProbabilitySector(
                            from_direction_degrees = 0, 
                            to_direction_degrees = 0, 
                            atmospheric_condition_class_ids = [
                                ''
                                ], 
                            probability_for_classes = [
                                1.337
                                ], )
                        ], )
            )
        else:
            return ComprehensiveSiteClassification(
        )
        """

    def testComprehensiveSiteClassification(self):
        """Test ComprehensiveSiteClassification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
