# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.project_info import ProjectInfo

class TestProjectInfo(unittest.TestCase):
    """ProjectInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectInfo:
        """Test ProjectInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectInfo`
        """
        model = ProjectInfo()
        if include_optional:
            return ProjectInfo(
                project_id = 'H0',
                site_latitude = -90,
                site_longitude = -180
            )
        else:
            return ProjectInfo(
                project_id = 'H0',
                site_latitude = -90,
                site_longitude = -180,
        )
        """

    def testProjectInfo(self):
        """Test ProjectInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
