# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.sensitivity_curve_calculation_outputs import SensitivityCurveCalculationOutputs

class TestSensitivityCurveCalculationOutputs(unittest.TestCase):
    """SensitivityCurveCalculationOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensitivityCurveCalculationOutputs:
        """Test SensitivityCurveCalculationOutputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensitivityCurveCalculationOutputs`
        """
        model = SensitivityCurveCalculationOutputs()
        if include_optional:
            return SensitivityCurveCalculationOutputs(
                overall_sensitivity_curve = dnv_windfarmer_client.models.overall_sensitivity_curve.OverallSensitivityCurve(
                    entries = [
                        dnv_windfarmer_client.models.sensitivity_curve_entry.SensitivityCurveEntry(
                            wind_speed_perturbation = 1.337, 
                            power_mw = 1.337, 
                            energy_perturbation = 1.337, )
                        ], ),
                wind_climate_sensitivity_curves = [
                    dnv_windfarmer_client.models.wind_climate_sensitivity_curve.WindClimateSensitivityCurve(
                        wind_climate_id = '', 
                        entries = [
                            dnv_windfarmer_client.models.sensitivity_curve_entry.SensitivityCurveEntry(
                                wind_speed_perturbation = 1.337, 
                                power_mw = 1.337, 
                                energy_perturbation = 1.337, )
                            ], )
                    ],
                turbine_sensitivity_curves = [
                    dnv_windfarmer_client.models.turbine_sensitivity_curve.TurbineSensitivityCurve(
                        wind_farm = '', 
                        turbine = '', 
                        entries = [
                            dnv_windfarmer_client.models.sensitivity_curve_entry.SensitivityCurveEntry(
                                wind_speed_perturbation = 1.337, 
                                power_mw = 1.337, 
                                energy_perturbation = 1.337, )
                            ], )
                    ]
            )
        else:
            return SensitivityCurveCalculationOutputs(
        )
        """

    def testSensitivityCurveCalculationOutputs(self):
        """Test SensitivityCurveCalculationOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
