# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.beet_model_input import BeetModelInput

class TestBeetModelInput(unittest.TestCase):
    """BeetModelInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeetModelInput:
        """Test BeetModelInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeetModelInput`
        """
        model = BeetModelInput()
        if include_optional:
            return BeetModelInput(
                turbines = [
                    dnv_windfarmer_client.models.turbine_location.TurbineLocation(
                        easting_m = 1.337, 
                        northing_m = 1.337, 
                        hub_height_m = 1.337, 
                        rotor_diameter_m = 1.337, )
                    ],
                turbine_performance = [
                    dnv_windfarmer_client.models.turbine_performance.TurbinePerformance(
                        wind_speed_m_per_s = 1.337, 
                        power_output_k_w = 1.337, 
                        thrust_coefficient = 1.337, 
                        frequency_pc = 1.337, )
                    ],
                significant_atmospheric_stability = True
            )
        else:
            return BeetModelInput(
        )
        """

    def testBeetModelInput(self):
        """Test BeetModelInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
