# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.energy_calculation_inputs import EnergyCalculationInputs

class TestEnergyCalculationInputs(unittest.TestCase):
    """EnergyCalculationInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnergyCalculationInputs:
        """Test EnergyCalculationInputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnergyCalculationInputs`
        """
        model = EnergyCalculationInputs()
        if include_optional:
            return EnergyCalculationInputs(
                project_info = dnv_windfarmer_client.models.project_info.ProjectInfo(
                    project_id = 'H0', 
                    site_latitude = -90, 
                    site_longitude = -180, ),
                wind_farms = [
                    dnv_windfarmer_client.models.wind_farm.WindFarm(
                        name = 'k$>x u&K}qz^sEC(lJ)<,j', 
                        turbines = [
                            dnv_windfarmer_client.models.turbine.Turbine(
                                name = 'k$>x u&K}qz^sEC(lJ)<,j', 
                                associated_wind_climate_id = '', 
                                turbine_model_id = '', 
                                is_installed = True, 
                                production_yield = 1.337, 
                                confidence_weighting = 1.337, 
                                location = null, 
                                curtailment_rules = [
                                    dnv_windfarmer_client.models.turbine_management_rule.TurbineManagementRule(
                                        wind_direction_from = 1.337, 
                                        wind_direction_to = 1.337, 
                                        minimum_wind_speed_m_per_s = 1.337, 
                                        maximum_wind_speed_m_per_s = 1.337, 
                                        time_from_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_from_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_from_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        start_day_of_year = 56, 
                                        end_day_of_year = 56, 
                                        minimum_temperature_degrees_celsius = 1.337, 
                                        maximum_temperature_degrees_celsius = 1.337, 
                                        active_mode = '', )
                                    ], 
                                park_wake_decay_constant = 1.337, )
                            ], 
                        is_neighbor = True, 
                        include_in_blockage_calculation = True, )
                    ],
                turbine_models = [
                    dnv_windfarmer_client.models.turbine_model.TurbineModel(
                        id = '', 
                        rotor_diameter_m = 1.337, 
                        number_of_blades = 56, 
                        hub_height_m = 1.337, 
                        performance_data = [
                            dnv_windfarmer_client.models.turbine_model_performance.TurbineModelPerformance(
                                turbine_operational_mode = 'normal', 
                                adjusted_high_speed_cut_out_m_per_s = 1.337, 
                                adjusted_low_speed_cut_in_m_per_s = 1.337, 
                                low_speed_cut_in_m_per_s = 1.337, 
                                high_speed_cut_out_m_per_s = 1.337, 
                                turbulence_intensity = 1.337, 
                                air_density_kg_per_m3 = 1.337, 
                                temperature_deg_c = 1.337, 
                                yaw_misalignment_degrees = 1.337, 
                                power_derating_delta_k_w = 1.337, 
                                performance_data_points = [
                                    dnv_windfarmer_client.models.turbine_model_performance_data_point.TurbineModelPerformanceDataPoint(
                                        wind_speed_m_per_s = 1.337, 
                                        power_output_w = 1.337, 
                                        rotor_speed_radians_per_s = 1.337, 
                                        thrust_coefficient = 1.337, 
                                        noise_difference_from_reference_curve_d_b = 1.337, )
                                    ], )
                            ], 
                        power_control = null, 
                        wind_speed_class = null, 
                        turbulence_intensity_class = null, 
                        reference_noise_level = 1.337, )
                    ],
                wind_climates = [
                    dnv_windfarmer_client.models.wind_climate.WindClimate(
                        id = '', 
                        location = null, 
                        height_above_ground_m = 1.337, 
                        number_of_direction_sectors = 56, 
                        direction_for_first_bin_centre_degrees = 1.337, 
                        wind_speed_bin_upper_limits_m_per_s = [
                            1.337
                            ], 
                        probability_distribution = [
                            [
                                1.337
                                ]
                            ], 
                        turbulence_intensity = [
                            [
                                1.337
                                ]
                            ], )
                    ],
                weibull_wind_climates = [
                    dnv_windfarmer_client.models.weibull_wind_climate.WeibullWindClimate(
                        id = '', 
                        location = null, 
                        height_above_ground_m = 1.337, 
                        number_of_direction_sectors = 56, 
                        direction_for_first_bin_centre_degrees = 1.337, 
                        sector_weibull_parameters = [
                            dnv_windfarmer_client.models.weibull_sector_parameters.WeibullSectorParameters(
                                a = 0, 
                                k = 0, 
                                probability = 0, )
                            ], 
                        turbulence_intensity = 0, )
                    ],
                atmospheric_conditions = dnv_windfarmer_client.models.atmospheric_conditions.AtmosphericConditions(
                    atmospheric_condition_classes = [
                        dnv_windfarmer_client.models.atmospheric_condition_class.AtmosphericConditionClass(
                            id = '', 
                            boundary_layer_height_m = 1, 
                            lapse_rate_k_per_100m = 0, 
                            delta_theta_across_inversion_layer_k = 0, 
                            thickness_inversion_layer_m = 0, 
                            heights_above_surface_m = [
                                1.337
                                ], 
                            turbulence_intensity_profile = [
                                1.337
                                ], 
                            wind_speed_vertical_gradient_profile_per_s_m = [
                                1.337
                                ], )
                        ], 
                    atmospheric_condition_probability_distribution = [
                        dnv_windfarmer_client.models.atmospheric_condition_probability_sector.AtmosphericConditionProbabilitySector(
                            from_direction_degrees = 0, 
                            to_direction_degrees = 0, 
                            atmospheric_condition_class_ids = [
                                ''
                                ], 
                            probability_for_classes = [
                                1.337
                                ], )
                        ], ),
                reference_air_density = dnv_windfarmer_client.models.reference_air_density.ReferenceAirDensity(
                    air_density_kg_per_m3 = 1.337, 
                    lapse_rate_kg_per_m3_per_m = 1.337, 
                    elevation_m = 1.337, ),
                flow_model = dnv_windfarmer_client.models.flow_model.FlowModel(
                    reference_directions_degrees = [
                        1.337
                        ], 
                    speeds_ups = [
                        dnv_windfarmer_client.models.speed_ups_for_location.SpeedUpsForLocation(
                            id = '', 
                            easting_m = 1.337, 
                            northing_m = 1.337, 
                            height_above_ground_m = 1.337, 
                            speed_ups = [
                                1.337
                                ], 
                            is_target = True, )
                        ], ),
                energy_efficiencies_settings = dnv_windfarmer_client.models.energy_efficiencies_settings.EnergyEfficienciesSettings(
                    calculate_efficiencies = True, 
                    calculate_ideal_yield = True, 
                    calculate_sensitivity_curve = True, 
                    include_hysteresis_effect = True, 
                    include_curtailment_rules = True, 
                    turbine_flow_and_performance_matrix_output_settings = null, 
                    number_of_direction_sectors_for_wake_calculation = 56, 
                    maximum_wind_speed_for_evaluation_m_per_s = 1.337, 
                    extrapolation_ambient_turbulence = null, 
                    air_density_correction_method = null, 
                    wake_model = null, 
                    blockage_model = null, )
            )
        else:
            return EnergyCalculationInputs(
                project_info = dnv_windfarmer_client.models.project_info.ProjectInfo(
                    project_id = 'H0', 
                    site_latitude = -90, 
                    site_longitude = -180, ),
                wind_farms = [
                    dnv_windfarmer_client.models.wind_farm.WindFarm(
                        name = 'k$>x u&K}qz^sEC(lJ)<,j', 
                        turbines = [
                            dnv_windfarmer_client.models.turbine.Turbine(
                                name = 'k$>x u&K}qz^sEC(lJ)<,j', 
                                associated_wind_climate_id = '', 
                                turbine_model_id = '', 
                                is_installed = True, 
                                production_yield = 1.337, 
                                confidence_weighting = 1.337, 
                                location = null, 
                                curtailment_rules = [
                                    dnv_windfarmer_client.models.turbine_management_rule.TurbineManagementRule(
                                        wind_direction_from = 1.337, 
                                        wind_direction_to = 1.337, 
                                        minimum_wind_speed_m_per_s = 1.337, 
                                        maximum_wind_speed_m_per_s = 1.337, 
                                        time_from_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_from_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_from_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        time_to_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                                        start_day_of_year = 56, 
                                        end_day_of_year = 56, 
                                        minimum_temperature_degrees_celsius = 1.337, 
                                        maximum_temperature_degrees_celsius = 1.337, 
                                        active_mode = '', )
                                    ], 
                                park_wake_decay_constant = 1.337, )
                            ], 
                        is_neighbor = True, 
                        include_in_blockage_calculation = True, )
                    ],
                turbine_models = [
                    dnv_windfarmer_client.models.turbine_model.TurbineModel(
                        id = '', 
                        rotor_diameter_m = 1.337, 
                        number_of_blades = 56, 
                        hub_height_m = 1.337, 
                        performance_data = [
                            dnv_windfarmer_client.models.turbine_model_performance.TurbineModelPerformance(
                                turbine_operational_mode = 'normal', 
                                adjusted_high_speed_cut_out_m_per_s = 1.337, 
                                adjusted_low_speed_cut_in_m_per_s = 1.337, 
                                low_speed_cut_in_m_per_s = 1.337, 
                                high_speed_cut_out_m_per_s = 1.337, 
                                turbulence_intensity = 1.337, 
                                air_density_kg_per_m3 = 1.337, 
                                temperature_deg_c = 1.337, 
                                yaw_misalignment_degrees = 1.337, 
                                power_derating_delta_k_w = 1.337, 
                                performance_data_points = [
                                    dnv_windfarmer_client.models.turbine_model_performance_data_point.TurbineModelPerformanceDataPoint(
                                        wind_speed_m_per_s = 1.337, 
                                        power_output_w = 1.337, 
                                        rotor_speed_radians_per_s = 1.337, 
                                        thrust_coefficient = 1.337, 
                                        noise_difference_from_reference_curve_d_b = 1.337, )
                                    ], )
                            ], 
                        power_control = null, 
                        wind_speed_class = null, 
                        turbulence_intensity_class = null, 
                        reference_noise_level = 1.337, )
                    ],
                reference_air_density = dnv_windfarmer_client.models.reference_air_density.ReferenceAirDensity(
                    air_density_kg_per_m3 = 1.337, 
                    lapse_rate_kg_per_m3_per_m = 1.337, 
                    elevation_m = 1.337, ),
                flow_model = dnv_windfarmer_client.models.flow_model.FlowModel(
                    reference_directions_degrees = [
                        1.337
                        ], 
                    speeds_ups = [
                        dnv_windfarmer_client.models.speed_ups_for_location.SpeedUpsForLocation(
                            id = '', 
                            easting_m = 1.337, 
                            northing_m = 1.337, 
                            height_above_ground_m = 1.337, 
                            speed_ups = [
                                1.337
                                ], 
                            is_target = True, )
                        ], ),
                energy_efficiencies_settings = dnv_windfarmer_client.models.energy_efficiencies_settings.EnergyEfficienciesSettings(
                    calculate_efficiencies = True, 
                    calculate_ideal_yield = True, 
                    calculate_sensitivity_curve = True, 
                    include_hysteresis_effect = True, 
                    include_curtailment_rules = True, 
                    turbine_flow_and_performance_matrix_output_settings = null, 
                    number_of_direction_sectors_for_wake_calculation = 56, 
                    maximum_wind_speed_for_evaluation_m_per_s = 1.337, 
                    extrapolation_ambient_turbulence = null, 
                    air_density_correction_method = null, 
                    wake_model = null, 
                    blockage_model = null, ),
        )
        """

    def testEnergyCalculationInputs(self):
        """Test EnergyCalculationInputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
