# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.wind_farm_aep_output import WindFarmAepOutput

class TestWindFarmAepOutput(unittest.TestCase):
    """WindFarmAepOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WindFarmAepOutput:
        """Test WindFarmAepOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WindFarmAepOutput`
        """
        model = WindFarmAepOutput()
        if include_optional:
            return WindFarmAepOutput(
                wind_farm_name = '',
                gross_annual_energy_yield_mwh_per_year = 1.337,
                ideal_annual_energy_yield_mwh_per_year = 1.337,
                internal_blockage_on_annual_energy_yield_mwh_per_year = 1.337,
                blockage_on_annual_energy_yield_mwh_per_year = 1.337,
                internal_wakes_on_annual_energy_yield_mwh_per_year = 1.337,
                hysteresis_adjustment_on_annual_energy_yield_mwh_per_year = 1.337,
                large_wind_farm_correction_on_annual_energy_yield_mwh_per_year = 1.337,
                neighbors_wakes_on_annual_energy_yield_mwh_per_year = 1.337,
                full_annual_energy_yield_mwh_per_year = 1.337,
                turbine_results = [
                    dnv_windfarmer_client.models.turbine_result.TurbineResult(
                        turbine_name = '', 
                        turbine_location = null, 
                        wind_farm_name = '', 
                        ideal_annual_yield_mwh_per_year = 1.337, 
                        gross_annual_yield_mwh_per_year = 1.337, 
                        internal_blockage_on_annual_yield_mwh_per_year = 1.337, 
                        blockage_on_annual_yield_mwh_per_year = 1.337, 
                        internal_wakes_on_annual_yield_mwh_per_year = 1.337, 
                        hysteresis_adjustment_on_annual_yield_mwh_per_year = 1.337, 
                        large_wind_farm_correction_on_annual_yield_mwh_per_year = 1.337, 
                        neighbors_wakes_on_annual_yield_mwh_per_year = 1.337, 
                        full_annual_yield_mwh_per_year = 1.337, 
                        tuning_annual_yield_mwh_per_year = 1.337, 
                        mean_turbulence_intensity = {
                            'key' : 1.337
                            }, 
                        free_mean_wind_speed_m_per_s = 1.337, 
                        full_mean_wind_speed_m_per_s = 1.337, 
                        ambient_mean_turbulence_intensity_percentage = 1.337, 
                        full_mean_turbulence_intensity_percentage = 1.337, 
                        air_density_at_hub_height_kg_per_m3 = 1.337, 
                        used_performance_table_ids = [
                            ''
                            ], )
                    ],
                turbine_flow_and_performance_matrices_with_mast_binning = [
                    dnv_windfarmer_client.models.turbine_flow_and_performance_matrix.TurbineFlowAndPerformanceMatrix(
                        turbine_name = '', 
                        wind_farm_name = '', 
                        direction_for_first_bin_centre_degrees = 1.337, 
                        bin_center_wind_speeds_at_mast_m_per_s = [
                            1.337
                            ], 
                        ambient_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        ambient_turbulence_intensity_percentage = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_center_line_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_width = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_offset_m = [
                            [
                                1.337
                                ]
                            ], 
                        waked_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        atmospheric_condition_aware_waked_wind_speed_m_per_s = {
                            'key' : [
                                [
                                    1.337
                                    ]
                                ]
                            }, 
                        waked_turbulence_intensity_percentage = [
                            [
                                1.337
                                ]
                            ], 
                        spot_power_output_w = [
                            [
                                1.337
                                ]
                            ], 
                        atmospheric_condition_aware_spot_power_output_w = {
                            'key' : [
                                null
                                ]
                            }, 
                        bin_power_output_w = [
                            [
                                1.337
                                ]
                            ], 
                        probability_distribution = [
                            [
                                1.337
                                ]
                            ], 
                        upstream_turbine_causing_wake = [
                            [
                                ''
                                ]
                            ], 
                        turbine_operational_mode = [
                            [
                                ''
                                ]
                            ], 
                        mast_to_turbine_speed_up = [
                            1.337
                            ], )
                    ],
                turbine_flow_and_performance_matrices_with_turbine_binning = [
                    dnv_windfarmer_client.models.turbine_flow_and_performance_matrix.TurbineFlowAndPerformanceMatrix(
                        turbine_name = '', 
                        wind_farm_name = '', 
                        direction_for_first_bin_centre_degrees = 1.337, 
                        bin_center_wind_speeds_at_mast_m_per_s = [
                            1.337
                            ], 
                        ambient_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        ambient_turbulence_intensity_percentage = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_center_line_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_width = [
                            [
                                1.337
                                ]
                            ], 
                        dominant_wake_offset_m = [
                            [
                                1.337
                                ]
                            ], 
                        waked_wind_speed_m_per_s = [
                            [
                                1.337
                                ]
                            ], 
                        atmospheric_condition_aware_waked_wind_speed_m_per_s = {
                            'key' : [
                                [
                                    1.337
                                    ]
                                ]
                            }, 
                        waked_turbulence_intensity_percentage = [
                            [
                                1.337
                                ]
                            ], 
                        spot_power_output_w = [
                            [
                                1.337
                                ]
                            ], 
                        atmospheric_condition_aware_spot_power_output_w = {
                            'key' : [
                                null
                                ]
                            }, 
                        bin_power_output_w = [
                            [
                                1.337
                                ]
                            ], 
                        probability_distribution = [
                            [
                                1.337
                                ]
                            ], 
                        upstream_turbine_causing_wake = [
                            [
                                ''
                                ]
                            ], 
                        turbine_operational_mode = [
                            [
                                ''
                                ]
                            ], 
                        mast_to_turbine_speed_up = [
                            1.337
                            ], )
                    ]
            )
        else:
            return WindFarmAepOutput(
        )
        """

    def testWindFarmAepOutput(self):
        """Test WindFarmAepOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
