# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_performance import TurbinePerformance

class TestTurbinePerformance(unittest.TestCase):
    """TurbinePerformance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbinePerformance:
        """Test TurbinePerformance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbinePerformance`
        """
        model = TurbinePerformance()
        if include_optional:
            return TurbinePerformance(
                wind_speed_m_per_s = 1.337,
                power_output_k_w = 1.337,
                thrust_coefficient = 1.337,
                frequency_pc = 1.337
            )
        else:
            return TurbinePerformance(
        )
        """

    def testTurbinePerformance(self):
        """Test TurbinePerformance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
