# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.wake_profile_integration_method import WakeProfileIntegrationMethod

class TestWakeProfileIntegrationMethod(unittest.TestCase):
    """WakeProfileIntegrationMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWakeProfileIntegrationMethod(self):
        """Test WakeProfileIntegrationMethod"""
        # inst = WakeProfileIntegrationMethod()

if __name__ == '__main__':
    unittest.main()
