# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_blockage_efficiency import TurbineBlockageEfficiency

class TestTurbineBlockageEfficiency(unittest.TestCase):
    """TurbineBlockageEfficiency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineBlockageEfficiency:
        """Test TurbineBlockageEfficiency
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineBlockageEfficiency`
        """
        model = TurbineBlockageEfficiency()
        if include_optional:
            return TurbineBlockageEfficiency(
                turbine_name = '',
                blockage_efficiency = 1.337
            )
        else:
            return TurbineBlockageEfficiency(
                turbine_name = '',
                blockage_efficiency = 1.337,
        )
        """

    def testTurbineBlockageEfficiency(self):
        """Test TurbineBlockageEfficiency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
