# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_local_wind_speeds_output_settings import TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings

class TestTurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(unittest.TestCase):
    """TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings:
        """Test TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings`
        """
        model = TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings()
        if include_optional:
            return TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(
                output_power_output = True,
                output_waked_wind_speed = True,
                output_probability_distribution = True,
                output_waked_turbulence_intensity = True,
                output_ambient_turbulence_intensity = True,
                output_operational_mode = True
            )
        else:
            return TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(
        )
        """

    def testTurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(self):
        """Test TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
