# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_management_rule import TurbineManagementRule

class TestTurbineManagementRule(unittest.TestCase):
    """TurbineManagementRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineManagementRule:
        """Test TurbineManagementRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineManagementRule`
        """
        model = TurbineManagementRule()
        if include_optional:
            return TurbineManagementRule(
                wind_direction_from = 1.337,
                wind_direction_to = 1.337,
                minimum_wind_speed_m_per_s = 1.337,
                maximum_wind_speed_m_per_s = 1.337,
                time_from_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33',
                time_to_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33',
                time_from_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33',
                time_to_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33',
                time_from_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33',
                time_to_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33',
                start_day_of_year = 56,
                end_day_of_year = 56,
                minimum_temperature_degrees_celsius = 1.337,
                maximum_temperature_degrees_celsius = 1.337,
                active_mode = ''
            )
        else:
            return TurbineManagementRule(
        )
        """

    def testTurbineManagementRule(self):
        """Test TurbineManagementRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
