# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.cfdml_wind_speed_extrapolation_model import CfdmlWindSpeedExtrapolationModel

class TestCfdmlWindSpeedExtrapolationModel(unittest.TestCase):
    """CfdmlWindSpeedExtrapolationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCfdmlWindSpeedExtrapolationModel(self):
        """Test CfdmlWindSpeedExtrapolationModel"""
        # inst = CfdmlWindSpeedExtrapolationModel()

if __name__ == '__main__':
    unittest.main()
