# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbulence_intensity_class import TurbulenceIntensityClass

class TestTurbulenceIntensityClass(unittest.TestCase):
    """TurbulenceIntensityClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTurbulenceIntensityClass(self):
        """Test TurbulenceIntensityClass"""
        # inst = TurbulenceIntensityClass()

if __name__ == '__main__':
    unittest.main()
