# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.extrapolation_ambient_turbulence import ExtrapolationAmbientTurbulence

class TestExtrapolationAmbientTurbulence(unittest.TestCase):
    """ExtrapolationAmbientTurbulence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtrapolationAmbientTurbulence(self):
        """Test ExtrapolationAmbientTurbulence"""
        # inst = ExtrapolationAmbientTurbulence()

if __name__ == '__main__':
    unittest.main()
