# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.eddy_viscosity import EddyViscosity

class TestEddyViscosity(unittest.TestCase):
    """EddyViscosity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EddyViscosity:
        """Test EddyViscosity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EddyViscosity`
        """
        model = EddyViscosity()
        if include_optional:
            return EddyViscosity(
                use_large_wind_farm_model = True,
                large_wind_farm_correction_parameters = dnv_windfarmer_client.models.large_wind_farm_correction_parameters.LargeWindFarmCorrectionParameters(
                    base_roughness_z01 = 1.337, 
                    increased_roughness_z02 = 1.337, 
                    geometric_width_diameters = 1.337, 
                    recovery_start_diameters = 1.337, 
                    fifty_percent_recovery_diameters = 1.337, ),
                use_closely_spaced_turbines_wake_modification = True,
                wake_profile_integration_method = 'Simpsons'
            )
        else:
            return EddyViscosity(
        )
        """

    def testEddyViscosity(self):
        """Test EddyViscosity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
