# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix import TurbineFlowAndPerformanceMatrix

class TestTurbineFlowAndPerformanceMatrix(unittest.TestCase):
    """TurbineFlowAndPerformanceMatrix unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineFlowAndPerformanceMatrix:
        """Test TurbineFlowAndPerformanceMatrix
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineFlowAndPerformanceMatrix`
        """
        model = TurbineFlowAndPerformanceMatrix()
        if include_optional:
            return TurbineFlowAndPerformanceMatrix(
                turbine_name = '',
                wind_farm_name = '',
                direction_for_first_bin_centre_degrees = 1.337,
                bin_center_wind_speeds_at_mast_m_per_s = [
                    1.337
                    ],
                ambient_wind_speed_m_per_s = [
                    [
                        1.337
                        ]
                    ],
                ambient_turbulence_intensity_percentage = [
                    [
                        1.337
                        ]
                    ],
                dominant_wake_center_line_wind_speed_m_per_s = [
                    [
                        1.337
                        ]
                    ],
                dominant_wake_width = [
                    [
                        1.337
                        ]
                    ],
                dominant_wake_offset_m = [
                    [
                        1.337
                        ]
                    ],
                waked_wind_speed_m_per_s = [
                    [
                        1.337
                        ]
                    ],
                atmospheric_condition_aware_waked_wind_speed_m_per_s = {
                    'key' : [
                        [
                            1.337
                            ]
                        ]
                    },
                waked_turbulence_intensity_percentage = [
                    [
                        1.337
                        ]
                    ],
                spot_power_output_w = [
                    [
                        1.337
                        ]
                    ],
                atmospheric_condition_aware_spot_power_output_w = {
                    'key' : [
                        null
                        ]
                    },
                bin_power_output_w = [
                    [
                        1.337
                        ]
                    ],
                probability_distribution = [
                    [
                        1.337
                        ]
                    ],
                upstream_turbine_causing_wake = [
                    [
                        ''
                        ]
                    ],
                turbine_operational_mode = [
                    [
                        ''
                        ]
                    ],
                mast_to_turbine_speed_up = [
                    1.337
                    ]
            )
        else:
            return TurbineFlowAndPerformanceMatrix(
        )
        """

    def testTurbineFlowAndPerformanceMatrix(self):
        """Test TurbineFlowAndPerformanceMatrix"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
