# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.wind_speed_class import WindSpeedClass

class TestWindSpeedClass(unittest.TestCase):
    """WindSpeedClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWindSpeedClass(self):
        """Test WindSpeedClass"""
        # inst = WindSpeedClass()

if __name__ == '__main__':
    unittest.main()
