# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine import Turbine

class TestTurbine(unittest.TestCase):
    """Turbine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Turbine:
        """Test Turbine
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Turbine`
        """
        model = Turbine()
        if include_optional:
            return Turbine(
                name = 'k$>x u&K}qz^sEC(lJ)<,j',
                associated_wind_climate_id = '',
                turbine_model_id = '',
                is_installed = True,
                production_yield = 1.337,
                confidence_weighting = 1.337,
                location = dnv_windfarmer_client.models.location.Location(
                    easting_m = 1.337, 
                    northing_m = 1.337, 
                    terrain_height_above_sea_level_m = 1.337, ),
                curtailment_rules = [
                    dnv_windfarmer_client.models.turbine_management_rule.TurbineManagementRule(
                        wind_direction_from = 1.337, 
                        wind_direction_to = 1.337, 
                        minimum_wind_speed_m_per_s = 1.337, 
                        maximum_wind_speed_m_per_s = 1.337, 
                        time_from_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                        time_to_as_time_of_day = '-072888001528021798096225500850762068629.33:93:33', 
                        time_from_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                        time_to_as_sun_rise_offset = '-072888001528021798096225500850762068629.33:93:33', 
                        time_from_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                        time_to_as_sun_set_offset = '-072888001528021798096225500850762068629.33:93:33', 
                        start_day_of_year = 56, 
                        end_day_of_year = 56, 
                        minimum_temperature_degrees_celsius = 1.337, 
                        maximum_temperature_degrees_celsius = 1.337, 
                        active_mode = '', )
                    ],
                park_wake_decay_constant = 1.337
            )
        else:
            return Turbine(
                name = 'k$>x u&K}qz^sEC(lJ)<,j',
                associated_wind_climate_id = '',
                turbine_model_id = '',
                location = dnv_windfarmer_client.models.location.Location(
                    easting_m = 1.337, 
                    northing_m = 1.337, 
                    terrain_height_above_sea_level_m = 1.337, ),
        )
        """

    def testTurbine(self):
        """Test Turbine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
