# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.api.blockage_correction_api import BlockageCorrectionApi


class TestBlockageCorrectionApi(unittest.TestCase):
    """BlockageCorrectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlockageCorrectionApi()

    def tearDown(self) -> None:
        pass

    def test_blockage_correction_post(self) -> None:
        """Test case for blockage_correction_post

        Gets the blockage correction result for the given inputs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
