# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.energy_efficiencies_settings import EnergyEfficienciesSettings

class TestEnergyEfficienciesSettings(unittest.TestCase):
    """EnergyEfficienciesSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnergyEfficienciesSettings:
        """Test EnergyEfficienciesSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnergyEfficienciesSettings`
        """
        model = EnergyEfficienciesSettings()
        if include_optional:
            return EnergyEfficienciesSettings(
                calculate_efficiencies = True,
                calculate_ideal_yield = True,
                calculate_sensitivity_curve = True,
                include_hysteresis_effect = True,
                include_curtailment_rules = True,
                turbine_flow_and_performance_matrix_output_settings = dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_output_settings.TurbineFlowAndPerformanceMatrixOutputSettings(
                    output_mast_to_turbine_speed_up = True, 
                    output_ambient_wind_speed = True, 
                    output_ambient_turbulence_intensity = True, 
                    output_dominant_wake_center_line_wind_speed = True, 
                    output_dominant_wake_offset = True, 
                    output_dominant_wake_width = True, 
                    output_waked_wind_speed = True, 
                    output_atmospheric_aware_waked_wind_speed = True, 
                    output_waked_turbulence_intensity = True, 
                    output_power_output = True, 
                    output_atmospheric_aware_power_output = True, 
                    output_probability_distribution = True, 
                    output_upstream_turbine_causing_wake = True, 
                    output_operational_mode = True, 
                    local_turbine_wind_speeds_output_settings = null, ),
                number_of_direction_sectors_for_wake_calculation = 56,
                maximum_wind_speed_for_evaluation_m_per_s = 1.337,
                extrapolation_ambient_turbulence = 'ConstantWindSpeedStandardDeviation',
                air_density_correction_method = 'WindFarmer5',
                wake_model = dnv_windfarmer_client.models.wake_model_settings.WakeModelSettings(
                    wake_model_type = null, 
                    eddy_viscosity = null, 
                    modified_park = null, 
                    turb_o_park = null, 
                    cfdml = null, 
                    no_wake_model = null, ),
                blockage_model = dnv_windfarmer_client.models.blockage_model_settings.BlockageModelSettings(
                    blockage_model_type = null, 
                    beet = null, 
                    cfdml = null, )
            )
        else:
            return EnergyEfficienciesSettings(
                calculate_efficiencies = True,
                include_hysteresis_effect = True,
                include_curtailment_rules = True,
                turbine_flow_and_performance_matrix_output_settings = dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_output_settings.TurbineFlowAndPerformanceMatrixOutputSettings(
                    output_mast_to_turbine_speed_up = True, 
                    output_ambient_wind_speed = True, 
                    output_ambient_turbulence_intensity = True, 
                    output_dominant_wake_center_line_wind_speed = True, 
                    output_dominant_wake_offset = True, 
                    output_dominant_wake_width = True, 
                    output_waked_wind_speed = True, 
                    output_atmospheric_aware_waked_wind_speed = True, 
                    output_waked_turbulence_intensity = True, 
                    output_power_output = True, 
                    output_atmospheric_aware_power_output = True, 
                    output_probability_distribution = True, 
                    output_upstream_turbine_causing_wake = True, 
                    output_operational_mode = True, 
                    local_turbine_wind_speeds_output_settings = null, ),
                number_of_direction_sectors_for_wake_calculation = 56,
                maximum_wind_speed_for_evaluation_m_per_s = 1.337,
                wake_model = dnv_windfarmer_client.models.wake_model_settings.WakeModelSettings(
                    wake_model_type = null, 
                    eddy_viscosity = null, 
                    modified_park = null, 
                    turb_o_park = null, 
                    cfdml = null, 
                    no_wake_model = null, ),
                blockage_model = dnv_windfarmer_client.models.blockage_model_settings.BlockageModelSettings(
                    blockage_model_type = null, 
                    beet = null, 
                    cfdml = null, ),
        )
        """

    def testEnergyEfficienciesSettings(self):
        """Test EnergyEfficienciesSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
