# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.api.status_api import StatusApi


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatusApi()

    def tearDown(self) -> None:
        pass

    def test_status_get(self) -> None:
        """Test case for status_get

        Checks the status of the API and validates authentication.
        """
        pass


if __name__ == '__main__':
    unittest.main()
