# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.cfdml_blockage_settings import CfdmlBlockageSettings

class TestCfdmlBlockageSettings(unittest.TestCase):
    """CfdmlBlockageSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CfdmlBlockageSettings:
        """Test CfdmlBlockageSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CfdmlBlockageSettings`
        """
        model = CfdmlBlockageSettings()
        if include_optional:
            return CfdmlBlockageSettings(
                cfdml_settings = dnv_windfarmer_client.models.cfdml.Cfdml(
                    gnn_type = null, 
                    gnn_version = '1.1', 
                    extrapolation_model = null, ),
                include_intermediate_results = True,
                blockage_correction_application_method = 'OnEnergy'
            )
        else:
            return CfdmlBlockageSettings(
                cfdml_settings = dnv_windfarmer_client.models.cfdml.Cfdml(
                    gnn_type = null, 
                    gnn_version = '1.1', 
                    extrapolation_model = null, ),
        )
        """

    def testCfdmlBlockageSettings(self):
        """Test CfdmlBlockageSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
