# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.beet_model_output import BeetModelOutput

class TestBeetModelOutput(unittest.TestCase):
    """BeetModelOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeetModelOutput:
        """Test BeetModelOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeetModelOutput`
        """
        model = BeetModelOutput()
        if include_optional:
            return BeetModelOutput(
                blockage_effect = 1.337,
                density_rotor_diameters = 1.337,
                blockage_loss_ws = 1.337,
                hub_height_rotor_diameter_multiplier = 1.337
            )
        else:
            return BeetModelOutput(
        )
        """

    def testBeetModelOutput(self):
        """Test BeetModelOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
