# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_model import TurbineModel

class TestTurbineModel(unittest.TestCase):
    """TurbineModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineModel:
        """Test TurbineModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineModel`
        """
        model = TurbineModel()
        if include_optional:
            return TurbineModel(
                id = '',
                rotor_diameter_m = 1.337,
                number_of_blades = 56,
                hub_height_m = 1.337,
                performance_data = [
                    dnv_windfarmer_client.models.turbine_model_performance.TurbineModelPerformance(
                        turbine_operational_mode = 'normal', 
                        adjusted_high_speed_cut_out_m_per_s = 1.337, 
                        adjusted_low_speed_cut_in_m_per_s = 1.337, 
                        low_speed_cut_in_m_per_s = 1.337, 
                        high_speed_cut_out_m_per_s = 1.337, 
                        turbulence_intensity = 1.337, 
                        air_density_kg_per_m3 = 1.337, 
                        temperature_deg_c = 1.337, 
                        yaw_misalignment_degrees = 1.337, 
                        power_derating_delta_k_w = 1.337, 
                        performance_data_points = [
                            dnv_windfarmer_client.models.turbine_model_performance_data_point.TurbineModelPerformanceDataPoint(
                                wind_speed_m_per_s = 1.337, 
                                power_output_w = 1.337, 
                                rotor_speed_radians_per_s = 1.337, 
                                thrust_coefficient = 1.337, 
                                noise_difference_from_reference_curve_d_b = 1.337, )
                            ], )
                    ],
                power_control = 'Pitch',
                wind_speed_class = 'Class1',
                turbulence_intensity_class = 'ClassA',
                reference_noise_level = 1.337
            )
        else:
            return TurbineModel(
                id = '',
                rotor_diameter_m = 1.337,
                number_of_blades = 56,
                hub_height_m = 1.337,
                performance_data = [
                    dnv_windfarmer_client.models.turbine_model_performance.TurbineModelPerformance(
                        turbine_operational_mode = 'normal', 
                        adjusted_high_speed_cut_out_m_per_s = 1.337, 
                        adjusted_low_speed_cut_in_m_per_s = 1.337, 
                        low_speed_cut_in_m_per_s = 1.337, 
                        high_speed_cut_out_m_per_s = 1.337, 
                        turbulence_intensity = 1.337, 
                        air_density_kg_per_m3 = 1.337, 
                        temperature_deg_c = 1.337, 
                        yaw_misalignment_degrees = 1.337, 
                        power_derating_delta_k_w = 1.337, 
                        performance_data_points = [
                            dnv_windfarmer_client.models.turbine_model_performance_data_point.TurbineModelPerformanceDataPoint(
                                wind_speed_m_per_s = 1.337, 
                                power_output_w = 1.337, 
                                rotor_speed_radians_per_s = 1.337, 
                                thrust_coefficient = 1.337, 
                                noise_difference_from_reference_curve_d_b = 1.337, )
                            ], )
                    ],
                power_control = 'Pitch',
        )
        """

    def testTurbineModel(self):
        """Test TurbineModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
