# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.weibull_wind_climate import WeibullWindClimate

class TestWeibullWindClimate(unittest.TestCase):
    """WeibullWindClimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeibullWindClimate:
        """Test WeibullWindClimate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeibullWindClimate`
        """
        model = WeibullWindClimate()
        if include_optional:
            return WeibullWindClimate(
                id = '',
                location = dnv_windfarmer_client.models.location.Location(
                    easting_m = 1.337, 
                    northing_m = 1.337, 
                    terrain_height_above_sea_level_m = 1.337, ),
                height_above_ground_m = 1.337,
                number_of_direction_sectors = 56,
                direction_for_first_bin_centre_degrees = 1.337,
                sector_weibull_parameters = [
                    dnv_windfarmer_client.models.weibull_sector_parameters.WeibullSectorParameters(
                        a = 0, 
                        k = 0, 
                        probability = 0, )
                    ],
                turbulence_intensity = 0
            )
        else:
            return WeibullWindClimate(
                id = '',
                location = dnv_windfarmer_client.models.location.Location(
                    easting_m = 1.337, 
                    northing_m = 1.337, 
                    terrain_height_above_sea_level_m = 1.337, ),
                height_above_ground_m = 1.337,
                number_of_direction_sectors = 56,
                direction_for_first_bin_centre_degrees = 1.337,
                sector_weibull_parameters = [
                    dnv_windfarmer_client.models.weibull_sector_parameters.WeibullSectorParameters(
                        a = 0, 
                        k = 0, 
                        probability = 0, )
                    ],
                turbulence_intensity = 0,
        )
        """

    def testWeibullWindClimate(self):
        """Test WeibullWindClimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
