# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.wake_model_settings import WakeModelSettings

class TestWakeModelSettings(unittest.TestCase):
    """WakeModelSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WakeModelSettings:
        """Test WakeModelSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WakeModelSettings`
        """
        model = WakeModelSettings()
        if include_optional:
            return WakeModelSettings(
                wake_model_type = 'ModifiedPark',
                eddy_viscosity = dnv_windfarmer_client.models.eddy_viscosity.EddyViscosity(
                    use_large_wind_farm_model = True, 
                    large_wind_farm_correction_parameters = null, 
                    use_closely_spaced_turbines_wake_modification = True, 
                    wake_profile_integration_method = null, ),
                modified_park = dnv_windfarmer_client.models.modified_park.ModifiedPark(
                    use_large_wind_farm_model = True, 
                    large_wind_farm_correction_parameters = null, ),
                turb_o_park = dnv_windfarmer_client.models.turb_o_park.TurbOPark(
                    wake_expansion = 1.337, ),
                cfdml = dnv_windfarmer_client.models.cfdml.Cfdml(
                    gnn_type = null, 
                    gnn_version = '1.1', 
                    extrapolation_model = null, ),
                no_wake_model = dnv_windfarmer_client.models.no_wake_model.NoWakeModel(
                    use_large_wind_farm_model = True, 
                    large_wind_farm_correction_parameters = null, )
            )
        else:
            return WakeModelSettings(
        )
        """

    def testWakeModelSettings(self):
        """Test WakeModelSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
