# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.weibull_sector_parameters import WeibullSectorParameters

class TestWeibullSectorParameters(unittest.TestCase):
    """WeibullSectorParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeibullSectorParameters:
        """Test WeibullSectorParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeibullSectorParameters`
        """
        model = WeibullSectorParameters()
        if include_optional:
            return WeibullSectorParameters(
                a = 0,
                k = 0,
                probability = 0
            )
        else:
            return WeibullSectorParameters(
                a = 0,
                k = 0,
                probability = 0,
        )
        """

    def testWeibullSectorParameters(self):
        """Test WeibullSectorParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
