# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.atmospheric_condition_class import AtmosphericConditionClass

class TestAtmosphericConditionClass(unittest.TestCase):
    """AtmosphericConditionClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AtmosphericConditionClass:
        """Test AtmosphericConditionClass
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AtmosphericConditionClass`
        """
        model = AtmosphericConditionClass()
        if include_optional:
            return AtmosphericConditionClass(
                id = '',
                boundary_layer_height_m = 1,
                lapse_rate_k_per_100m = 0,
                delta_theta_across_inversion_layer_k = 0,
                thickness_inversion_layer_m = 0,
                heights_above_surface_m = [
                    1.337
                    ],
                turbulence_intensity_profile = [
                    1.337
                    ],
                wind_speed_vertical_gradient_profile_per_s_m = [
                    1.337
                    ]
            )
        else:
            return AtmosphericConditionClass(
                id = '',
                boundary_layer_height_m = 1,
                lapse_rate_k_per_100m = 0,
                delta_theta_across_inversion_layer_k = 0,
                thickness_inversion_layer_m = 0,
                heights_above_surface_m = [
                    1.337
                    ],
                turbulence_intensity_profile = [
                    1.337
                    ],
                wind_speed_vertical_gradient_profile_per_s_m = [
                    1.337
                    ],
        )
        """

    def testAtmosphericConditionClass(self):
        """Test AtmosphericConditionClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
