# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.blockage_model_settings import BlockageModelSettings

class TestBlockageModelSettings(unittest.TestCase):
    """BlockageModelSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlockageModelSettings:
        """Test BlockageModelSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlockageModelSettings`
        """
        model = BlockageModelSettings()
        if include_optional:
            return BlockageModelSettings(
                blockage_model_type = 'NoBlockageModel',
                beet = dnv_windfarmer_client.models.beet_settings.BeetSettings(
                    significant_atmospheric_stability = True, 
                    include_intermediate_results = True, 
                    inclusion_of_neighbors_buffer_zone_in_meters = 1.337, 
                    blockage_correction_application_method = null, ),
                cfdml = dnv_windfarmer_client.models.cfdml_blockage_settings.CfdmlBlockageSettings(
                    cfdml_settings = null, 
                    include_intermediate_results = True, 
                    blockage_correction_application_method = null, )
            )
        else:
            return BlockageModelSettings(
        )
        """

    def testBlockageModelSettings(self):
        """Test BlockageModelSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
