# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.atmospheric_condition_probability_sector import AtmosphericConditionProbabilitySector

class TestAtmosphericConditionProbabilitySector(unittest.TestCase):
    """AtmosphericConditionProbabilitySector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AtmosphericConditionProbabilitySector:
        """Test AtmosphericConditionProbabilitySector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AtmosphericConditionProbabilitySector`
        """
        model = AtmosphericConditionProbabilitySector()
        if include_optional:
            return AtmosphericConditionProbabilitySector(
                from_direction_degrees = 0,
                to_direction_degrees = 0,
                atmospheric_condition_class_ids = [
                    ''
                    ],
                probability_for_classes = [
                    1.337
                    ]
            )
        else:
            return AtmosphericConditionProbabilitySector(
                from_direction_degrees = 0,
                to_direction_degrees = 0,
                atmospheric_condition_class_ids = [
                    ''
                    ],
                probability_for_classes = [
                    1.337
                    ],
        )
        """

    def testAtmosphericConditionProbabilitySector(self):
        """Test AtmosphericConditionProbabilitySector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
