# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.blockage_model_type import BlockageModelType

class TestBlockageModelType(unittest.TestCase):
    """BlockageModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlockageModelType(self):
        """Test BlockageModelType"""
        # inst = BlockageModelType()

if __name__ == '__main__':
    unittest.main()
