# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.reference_air_density import ReferenceAirDensity

class TestReferenceAirDensity(unittest.TestCase):
    """ReferenceAirDensity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReferenceAirDensity:
        """Test ReferenceAirDensity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReferenceAirDensity`
        """
        model = ReferenceAirDensity()
        if include_optional:
            return ReferenceAirDensity(
                air_density_kg_per_m3 = 1.337,
                lapse_rate_kg_per_m3_per_m = 1.337,
                elevation_m = 1.337
            )
        else:
            return ReferenceAirDensity(
                air_density_kg_per_m3 = 1.337,
                lapse_rate_kg_per_m3_per_m = 1.337,
                elevation_m = 1.337,
        )
        """

    def testReferenceAirDensity(self):
        """Test ReferenceAirDensity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
