# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.weighted_cfdml_intermediate_data import WeightedCfdmlIntermediateData

class TestWeightedCfdmlIntermediateData(unittest.TestCase):
    """WeightedCfdmlIntermediateData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeightedCfdmlIntermediateData:
        """Test WeightedCfdmlIntermediateData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeightedCfdmlIntermediateData`
        """
        model = WeightedCfdmlIntermediateData()
        if include_optional:
            return WeightedCfdmlIntermediateData(
                intermediate_cfdml_v2_data = {
                    'key' : {
                        'key' : {
                            'key' : [
                                dnv_windfarmer_client.models.turbine_blockage_efficiency.TurbineBlockageEfficiency(
                                    turbine_name = '', 
                                    blockage_efficiency = 1.337, )
                                ]
                            }
                        }
                    },
                intermediate_cfdml_v1_data = {
                    'key' : {
                        'key' : [
                            dnv_windfarmer_client.models.turbine_blockage_efficiency.TurbineBlockageEfficiency(
                                turbine_name = '', 
                                blockage_efficiency = 1.337, )
                            ]
                        }
                    },
                training_set_alignment_metrics = dnv_windfarmer_client.models.cfdml_training_set_alignment_metrics.CfdmlTrainingSetAlignmentMetrics(
                    edges_below_min_perc = 1.337, 
                    edges_above_max_perc = 1.337, 
                    vertices_below_min_perc = 1.337, 
                    vertices_above_max_perc = 1.337, )
            )
        else:
            return WeightedCfdmlIntermediateData(
        )
        """

    def testWeightedCfdmlIntermediateData(self):
        """Test WeightedCfdmlIntermediateData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
