# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.api.annual_energy_production_api import AnnualEnergyProductionApi


class TestAnnualEnergyProductionApi(unittest.TestCase):
    """AnnualEnergyProductionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnnualEnergyProductionApi()

    def tearDown(self) -> None:
        pass

    def test_annual_energy_production_post(self) -> None:
        """Test case for annual_energy_production_post

        Gets the energy calculation result for the given inputs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
