# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_output_settings import TurbineFlowAndPerformanceMatrixOutputSettings

class TestTurbineFlowAndPerformanceMatrixOutputSettings(unittest.TestCase):
    """TurbineFlowAndPerformanceMatrixOutputSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineFlowAndPerformanceMatrixOutputSettings:
        """Test TurbineFlowAndPerformanceMatrixOutputSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineFlowAndPerformanceMatrixOutputSettings`
        """
        model = TurbineFlowAndPerformanceMatrixOutputSettings()
        if include_optional:
            return TurbineFlowAndPerformanceMatrixOutputSettings(
                output_mast_to_turbine_speed_up = True,
                output_ambient_wind_speed = True,
                output_ambient_turbulence_intensity = True,
                output_dominant_wake_center_line_wind_speed = True,
                output_dominant_wake_offset = True,
                output_dominant_wake_width = True,
                output_waked_wind_speed = True,
                output_atmospheric_aware_waked_wind_speed = True,
                output_waked_turbulence_intensity = True,
                output_power_output = True,
                output_atmospheric_aware_power_output = True,
                output_probability_distribution = True,
                output_upstream_turbine_causing_wake = True,
                output_operational_mode = True,
                local_turbine_wind_speeds_output_settings = dnv_windfarmer_client.models.turbine_flow_and_performance_matrix_local_wind_speeds_output_settings.TurbineFlowAndPerformanceMatrixLocalWindSpeedsOutputSettings(
                    output_power_output = True, 
                    output_waked_wind_speed = True, 
                    output_probability_distribution = True, 
                    output_waked_turbulence_intensity = True, 
                    output_ambient_turbulence_intensity = True, 
                    output_operational_mode = True, )
            )
        else:
            return TurbineFlowAndPerformanceMatrixOutputSettings(
        )
        """

    def testTurbineFlowAndPerformanceMatrixOutputSettings(self):
        """Test TurbineFlowAndPerformanceMatrixOutputSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
