# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.models.turbine_location import TurbineLocation

class TestTurbineLocation(unittest.TestCase):
    """TurbineLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TurbineLocation:
        """Test TurbineLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TurbineLocation`
        """
        model = TurbineLocation()
        if include_optional:
            return TurbineLocation(
                easting_m = 1.337,
                northing_m = 1.337,
                hub_height_m = 1.337,
                rotor_diameter_m = 1.337
            )
        else:
            return TurbineLocation(
        )
        """

    def testTurbineLocation(self):
        """Test TurbineLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
