# coding: utf-8

"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dnv_windfarmer_client.api.annual_energy_production_async_api import AnnualEnergyProductionAsyncApi


class TestAnnualEnergyProductionAsyncApi(unittest.TestCase):
    """AnnualEnergyProductionAsyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnnualEnergyProductionAsyncApi()

    def tearDown(self) -> None:
        pass

    def test_annual_energy_production_async_delete(self) -> None:
        """Test case for annual_energy_production_async_delete

        Cancels the running of a calculation for the given Id.
        """
        pass

    def test_annual_energy_production_async_get(self) -> None:
        """Test case for annual_energy_production_async_get

        Gets the status of an async AnnualEnergyProduction calculation.
        """
        pass

    def test_annual_energy_production_async_post(self) -> None:
        """Test case for annual_energy_production_async_post

        Queues an energy calculation to be executed with the given inputs.
        """
        pass


if __name__ == '__main__':
    unittest.main()
