"""
    WindFarmer Services API

    A DNV WindFarmer calculation services API.

    The version of the OpenAPI document: 3.3
    Contact: windfarmer@dnv.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field
from typing import Optional, Union
from typing_extensions import Annotated
from dnv_windfarmer_client.models.comprehensive_site_classification import ComprehensiveSiteClassification

from dnv_windfarmer_client.api_client import ApiClient, RequestSerialized
from dnv_windfarmer_client.api_response import ApiResponse
from dnv_windfarmer_client.rest import RESTResponseType


class AtmosphericConditionsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def atmospheric_conditions_get(
        self,
        lat: Annotated[Optional[Union[Annotated[float, Field(le=85, strict=True, ge=-85)], Annotated[int, Field(le=85, strict=True, ge=-85)]]], Field(description="Latitude of the site in decimal degrees (-85 to 85)")] = None,
        lon: Annotated[Optional[Union[Annotated[float, Field(le=180, strict=True, ge=-180)], Annotated[int, Field(le=180, strict=True, ge=-180)]]], Field(description="Longitude of the site in decimal degrees (-180 to 180)")] = None,
        radius: Annotated[Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0.1)], Annotated[int, Field(le=100, strict=True, ge=1)]]], Field(description="Analysis radius in kilometers (0-100, default: 50.0)")] = None,
        land_fraction_threshold: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Threshold for land classification (0.0-1.0, default: 0.2)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ComprehensiveSiteClassification:
        """Performs comprehensive site classification and returns atmospheric condition data compatible with WindFarmer.Calculations.DataModel for flow modeling applications. Includes atmospheric stability weights derived from ERA5 data and vertical profiles.


        :param lat: Latitude of the site in decimal degrees (-85 to 85)
        :type lat: float
        :param lon: Longitude of the site in decimal degrees (-180 to 180)
        :type lon: float
        :param radius: Analysis radius in kilometers (0-100, default: 50.0)
        :type radius: float
        :param land_fraction_threshold: Threshold for land classification (0.0-1.0, default: 0.2)
        :type land_fraction_threshold: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._atmospheric_conditions_get_serialize(
            lat=lat,
            lon=lon,
            radius=radius,
            land_fraction_threshold=land_fraction_threshold,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComprehensiveSiteClassification",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def atmospheric_conditions_get_with_http_info(
        self,
        lat: Annotated[Optional[Union[Annotated[float, Field(le=85, strict=True, ge=-85)], Annotated[int, Field(le=85, strict=True, ge=-85)]]], Field(description="Latitude of the site in decimal degrees (-85 to 85)")] = None,
        lon: Annotated[Optional[Union[Annotated[float, Field(le=180, strict=True, ge=-180)], Annotated[int, Field(le=180, strict=True, ge=-180)]]], Field(description="Longitude of the site in decimal degrees (-180 to 180)")] = None,
        radius: Annotated[Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0.1)], Annotated[int, Field(le=100, strict=True, ge=1)]]], Field(description="Analysis radius in kilometers (0-100, default: 50.0)")] = None,
        land_fraction_threshold: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Threshold for land classification (0.0-1.0, default: 0.2)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ComprehensiveSiteClassification]:
        """Performs comprehensive site classification and returns atmospheric condition data compatible with WindFarmer.Calculations.DataModel for flow modeling applications. Includes atmospheric stability weights derived from ERA5 data and vertical profiles.


        :param lat: Latitude of the site in decimal degrees (-85 to 85)
        :type lat: float
        :param lon: Longitude of the site in decimal degrees (-180 to 180)
        :type lon: float
        :param radius: Analysis radius in kilometers (0-100, default: 50.0)
        :type radius: float
        :param land_fraction_threshold: Threshold for land classification (0.0-1.0, default: 0.2)
        :type land_fraction_threshold: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._atmospheric_conditions_get_serialize(
            lat=lat,
            lon=lon,
            radius=radius,
            land_fraction_threshold=land_fraction_threshold,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComprehensiveSiteClassification",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def atmospheric_conditions_get_without_preload_content(
        self,
        lat: Annotated[Optional[Union[Annotated[float, Field(le=85, strict=True, ge=-85)], Annotated[int, Field(le=85, strict=True, ge=-85)]]], Field(description="Latitude of the site in decimal degrees (-85 to 85)")] = None,
        lon: Annotated[Optional[Union[Annotated[float, Field(le=180, strict=True, ge=-180)], Annotated[int, Field(le=180, strict=True, ge=-180)]]], Field(description="Longitude of the site in decimal degrees (-180 to 180)")] = None,
        radius: Annotated[Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0.1)], Annotated[int, Field(le=100, strict=True, ge=1)]]], Field(description="Analysis radius in kilometers (0-100, default: 50.0)")] = None,
        land_fraction_threshold: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Threshold for land classification (0.0-1.0, default: 0.2)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Performs comprehensive site classification and returns atmospheric condition data compatible with WindFarmer.Calculations.DataModel for flow modeling applications. Includes atmospheric stability weights derived from ERA5 data and vertical profiles.


        :param lat: Latitude of the site in decimal degrees (-85 to 85)
        :type lat: float
        :param lon: Longitude of the site in decimal degrees (-180 to 180)
        :type lon: float
        :param radius: Analysis radius in kilometers (0-100, default: 50.0)
        :type radius: float
        :param land_fraction_threshold: Threshold for land classification (0.0-1.0, default: 0.2)
        :type land_fraction_threshold: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._atmospheric_conditions_get_serialize(
            lat=lat,
            lon=lon,
            radius=radius,
            land_fraction_threshold=land_fraction_threshold,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComprehensiveSiteClassification",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _atmospheric_conditions_get_serialize(
        self,
        lat,
        lon,
        radius,
        land_fraction_threshold,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if lat is not None:
            
            _query_params.append(('Lat', lat))
            
        if lon is not None:
            
            _query_params.append(('Lon', lon))
            
        if radius is not None:
            
            _query_params.append(('Radius', radius))
            
        if land_fraction_threshold is not None:
            
            _query_params.append(('LandFractionThreshold', land_fraction_threshold))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'text/plain', 
                    'application/json', 
                    'text/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'Bearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/AtmosphericConditions',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


